### ISSUE TITLE
post with form-params and content-type json

### ISSUE THREAD

**Issue by violahs** [http-kit/http-kit#112]
I am programming against an internal REST API that requires a POST, with form-params, **and** content-type json.

I've verified that I can connect to the API, login, get cookies, and do other simple things.  I have written working code against this API in Python and have access to similar Ruby code.  

Here are two tries.  One using clj-http (which works) and the other http-kit, which does not.

```clojure
(defn post-weblink-http-kit [path cookies spot-id url title description]
  @(http-kit/post (str path "spots/" spot-id "/items")
              {:headers {"Cookie" cookies}
               :content-type :json  ; Ignored??
               :form-params {:item {:webLink {:url url :title title :description description}}}}))


(defn post-weblink-clj-http [path cookies spot-id url title description]
  (client/post (str path "spots/" spot-id "/items")
               {:cookies cookies
                :content-type :json
                :form-params {:item {:webLink {:url url :title title :description description}}}}))
```
(Note, the only real difference here is that the cookies for http-kit are raw and the cookies for clj-http are a map.  But I have verified that is not the issue.)

I have also tried explicitly constructing the json (which is what I needed to do in Python).  

```clojure
(defn post-weblink-json [path cookies spot-id url title description]
  @(http-kit/post (str path "spots/" spot-id "/items")
              {:headers {"Cookie" cookies}
               :content-type :json  ; Ignored??
               :form-params {:item (json/generate-string {:webLink {:url url :title title :description description}})}}))
```

Both http-kit calls give an error like this:

:body "\"757: unexpected token at 'item=%7B%22webLink%22%3A%7B%22url%22%3A%22http%3A%2F%2Fen.wikipedia.org%2Fwiki%2FNikola_Tesla%22%2C%22title%22%3A%22Nik+Tesla%22%2C%22description%22%3A%22foo+bar+baz%22%7D%7D'\""

Any thoughts on this??

**Comment by wxjeacen** [comment]
Indeed, 
I am also looking for the parms.  :body option.

**Comment by shaiguitar** [comment]
Hey,

I did a quick PR for this on the doc/website side of things: https://github.com/http-kit/http-kit.github.com/pull/24

Let me know if that works or if someone else has other thoughts. Either way, I ran into this same confusion as well so I think some kind of clarification somewhere would be nice.

**Comment by ptaoussanis** [comment]
Closing this, thanks for the docs PR!
