### ISSUE TITLE
http-kit defensive programming

### ISSUE THREAD

**Issue by txrev319** [http-kit/http-kit#114]
Hi,

## background

  Although the following includes as much details as possible, I admit that my question is rather vague (and not well formulated). The details should be taken as a general stab in the direction, not a concrete proposal.

  When opening up a websocket, can I specify the following options:

    {:in-bucket [number]
     :in-msg-size [number]
     :out-bucket [number]
     :retry-count [number]
     :timeout [number]
     :handler [function]}

Basically, I would like to specify the following:

  * what is the maximal # of unhandled incoming messages
(when the function registered by "httpkit/on-receive ws-chan ... " has been called, I consider the message "handled" -- before this is called, I consider the message "unhandled")

  * what is the maximal size of an incoming message
  * what is the maximal # of enqueued (but not yet sent to client) messages
  * max # of time sending a messsage to a client is retried
  * max time allowed for client to receive a message

  * and a handler error function to be called when any of the above is violated

Furthermore, I would like this on a _per websocket_ granularity. I don't want there to be a gigantic queue for all websockets -- I want per websocket control, so I can locate and kill troublesome websockets.

## question:

(1) is this possible to do with existing http-kit technology?

(2) if so, how? if not, is this something for the future?

The main issue here is: is there someway to get _per websocket_ control (rather than, say, one gigantic queue for all websockets).

Thanks!

**Comment by ptaoussanis** [comment]
Hi there, busy doing issue triage - is this question still relevant or can it be closed? Thanks!
