### ISSUE TITLE
Bind to any available port

### ISSUE THREAD

**Issue by wiseman** [http-kit/http-kit#121]
This is a feature request to be able to run a server without specifying a port, and have the ability to ask the server what port it's running on.

I realize this isn't a well-known use-case, but it is really handy for things like automating integration tests, and is a very common pattern in some groups (_cough_Google).

Currently I can pass port 0 to `run-server`, which will run the server on an available port, but there's no way I see to determine which port it's running on.

**Comment by MichaelDrogalis** [comment]
Super glad to see this was implemented. Thanks guys!
