### ISSUE TITLE
get a illegal char in path char is {

### ISSUE THREAD

**Issue by bww00** [http-kit/http-kit#135]
java.net.URISyntaxException: Illegal character in path at index 73: 
http://eas-abuild.hs.uab.edu/camm/abuild.hs.uab.edu/service/mediaContent/{bd-7a-24-0e-ad-ca-44-17-8e-f2-c7-ee-99-7e-02-44}>}>

the rest server that the requres is sending to uses { and } on this particular request to delimit specific content

**Comment by ptaoussanis** [comment]
Hi there, doing issue triage - is this question still relevant or can it be closed?

If you'd prefer it be kept open, please try clarify what you're asking exactly? What is generating this URL? How is http-kit involved? Do you expect a bug, or is this a usage question?

Thanks!

**Comment by nberger** [comment]
Just adding that curly braces `"{" | "}"` and angle-brackets `"<" | ">"` are invalid characters in a URI, so the exception makes sense. See http://greenbytes.de/tech/webdav/rfc2396.html#rfc.iref.u.19
