### ISSUE TITLE
Multiple cookie headers generate a 500 error

### ISSUE THREAD

**Issue by ramanb** [http-kit/http-kit#138]
Double Cookie Header
 
When two "Cookie" headers are sent, regardless of their value, a 500 is returned:
 
GET / HTTP/1.1
Host: 127.0.0.1
Cookie: test=123
Cookie: t123123=123

**Comment by ptaoussanis** [comment]
@Christopher-Bui Hi Christopher, busy doing issue triage - is this question still relevant or can the issue be closed? Thanks!
