### ISSUE TITLE
100% CPU + Heap maxed out (http-kit Server)

### ISSUE THREAD

**Issue by xsc** [http-kit/http-kit#165]
Let me lead with the fact that I, unfortunately, did not yet find a way to reproduce this issue but I've experienced it a few times in the last few weeks.

--
An http-kit server was running locally (and under next to no load) for around 12hrs before CPU usage spiked to 100% and the heap had only a few KB of memory left. I pulled a 2GB heap dump using VisualVM, showing that most of the allocated memory is used by `org.httpkit.server.PendingKey` (and the `ConcurrentLinkedQueue$Node`s that contain said keys):

![image](https://cloud.githubusercontent.com/assets/198072/4316731/f20051c8-3f0a-11e4-9293-16a3085cd427.png)

Further inspection shows that the majority of those `PendingKeys` are identical, having `Op` set to `1001` (representing `org.httpkit.server.Frame.CloseFrame.CLOSE_AWAY`).

![image](https://cloud.githubusercontent.com/assets/198072/4316905/c078d2d6-3f0c-11e4-9472-9cefa56e7a60.png)

Usage includes normal HTTP requests and WebSocket I/O with the latter's connection loss handling maybe being the culprit.

--
```bash
$ lein deps :tree | grep http-kit
   [http-kit "2.1.18"]
```

**Comment by ptaoussanis** [comment]
Hi @xsc, busy performing issue triage - should this issue still be open?

**Comment by xsc** [comment]
Hi Peter, thanks for doing this!

I didn't see any changes indicating that this was fixed - it might be reproducible by creating a websocket server, connecting a browser, then leaving it be for a (long) while. For me, personally, the problem disappeared after I added a small manual heartbeat mechanism to my websocket connections.

So, I guess, this is most likely still an issue, but - at least for me - there is a workaround.

**Comment by ptaoussanis** [comment]
Okay, thanks for the update Yannick!

**Comment by venantius** [comment]
It is my belief that this issue should have been resolved with the fix in #258; since prior to that it was possible to pile tons of PendingKeys (specifically for `CLOSE_NORMAL` and `CLOSE_AWAY`) on the queue without returning control to the `selector` consumer. 

@xsc - does that sound right?

**Comment by xsc** [comment]
@venantius Sounds right, indeed. Thanks!

**Comment by venantius** [comment]
Great :)

**Comment by venantius** [comment]
(didn't mean to re-open)
