### ISSUE TITLE
Sources for Version 2.1.19?

### ISSUE THREAD

**Issue by xsc** [http-kit/http-kit#170]
There seems to be version 2.1.19 in Clojars (https://clojars.org/http-kit) but there are no sources (or tags) in this repository that match that one.

**Comment by narma** [comment]
clojars points to this 6d99f1969ecfd378effae18fedcfa2ce33427f30 commit for the 2.1.19 version.

**Comment by xsc** [comment]
@narma That commit still has `2.1.18` in its `project.clj` - something is (and some other things might be) missing.

**Comment by narma** [comment]
@xsc But you can change version in `project.clj`, deploy to clojars, revert version and continue the developming.

**Comment by ptaoussanis** [comment]
Best guess we have at the moment and the dates seem to coincide, so have tagged 6d99f19 for now.
