### ISSUE TITLE
Duplicate Content-Length header breaks ring.middleware.not-modified in uberjar

### ISSUE THREAD

**Issue by Kungi** [http-kit/http-kit#174]
# Problem

I built a webapp containing ring.middleware.not-modified to help deliver my resources.
When using http-kit in conjunction with this middleware I get duplicate, sometimes differing Content-Length headers in the HTTP response. Everything works fine when I use `lein run` or run the application out of the REPL (let's call this the REPL case). But when I compile the application into an uberjar it breaks the middleware (uberjar case). Let's first have a look at the REPL case. See the following cURL examples:

# Examples

### Delivery case
    $ curl -I 'http://localhost:3000/bootstrap/css/bootstrap.min.css' -H 'Accept-Encoding: gzip,deflate,sdch' -H 'Accept-Language: en-US,en;q=0.8,de;q=0.6' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36' -H 'Accept: text/css,*/*;q=0.1' -H 'Referer: http://localhost:3000/infocenter/1/9f8a7d58-f757-40b5-8195-ed07064cba9a' -H 'Cookie: ring-session=736772b8-7eda-4d25-8adc-a7f3a6b17d1d; csrftoken=07UUQPM2CP3Ng1CEMpBvwqvffbK2QlHcDq7Cr5CxDugUmWCigsyl%2BVxm3e0ZMlvnxou9%2FbfEFnb2nogi' -H 'Connection: keep-alive' -H 'Cache-Control: max-age=0' --compressed
    HTTP/1.1 200 OK
    Set-Cookie: csrftoken=07UUQPM2CP3Ng1CEMpBvwqvffbK2QlHcDq7Cr5CxDugUmWCigsyl%2BVxm3e0ZMlvnxou9%2FbfEFnb2nogi;Path=/
    Content-Type: text/css
    Last-Modified: Fri, 30 May 2014 15:16:09 +0000
    Content-Length: 101595
    Content-Length: 0
    Server: http-kit
    Date: Tue, 07 Oct 2014 16:22:49 GMT

See the duplicate Content-Length headers with the different values. This works fine in the browser for some reason.

### Not modified case

    $ curl -I 'http://localhost:3000/bootstrap/css/bootstrap.min.css' -H 'Accept-Encoding: gzip,deflate,sdch' -H 'Accept-Language: en-US,en;q=0.8,de;q=0.6' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36' -H 'Accept: text/css,*/*;q=0.1' -H 'Referer: http://localhost:3000/login' -H 'Cookie: ring-session=4dce5bf5-0e7e-4f1b-81af-dd013b7f0d13; csrftoken=6SgmfAX6AaCVwkmfT58AXn7kzi7n%2BiYmObDnu3x58BrUCwoU%2FcQOvFUI5enzKT3Z1YuIJ7CS6kqfl7Fs' -H 'Connection: keep-alive' -H 'If-Modified-Since: Fri, 30 May 2014 15:16:09 +0000' -H 'Cache-Control: max-age=0' --compressed

    HTTP/1.1 304 Not Modified
    Set-Cookie: csrftoken=6SgmfAX6AaCVwkmfT58AXn7kzi7n%2BiYmObDnu3x58BrUCwoU%2FcQOvFUI5enzKT3Z1YuIJ7CS6kqfl7Fs;Path=/
    Content-Type: text/css
    Last-Modified: Fri, 30 May 2014 15:16:09 +0000
    Content-Length: 0
    Content-Length: 0
    Server: http-kit
    Date: Tue, 07 Oct 2014 16:05:24 GMT

In this case the Content-Length headers match such that there also is no problem.

### Delivery case

    $ curl -I 'http://localhost:40400/bootstrap/css/bootstrap.min.css' -H 'Accept: text/css,*/*;q=0.1' -H 'Referer: http://localhost:40400/login' -H 'X-DevTools-Emulate-Network-Conditions-Client-Id: A35742C9-1C67-620E-7D73-629A1F5B18B9' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36' --compressed
    HTTP/1.1 200 OK
    Set-Cookie: ring-session=05ad7777-4363-4499-a135-cdec44adeba5;Path=/
    Set-Cookie: csrftoken=YFrRC43wfLeW7HTZ6FvU6p7L63oyrECIscvyMIzyMCfkSvAoTH%2FwNGTt0F1TR18OoCJLxogRaYjYi%2Fkt;Path=/
    Content-Type: text/css
    Last-Modified: Tue, 07 Oct 2014 14:36:50 GMT
    Content-Length: 101595
    Content-Length: 0
    Server: http-kit
    Date: Tue, 07 Oct 2014 16:19:56 GMT

This case looks exactly the same as the REPL/delivery case and also works.

### Not modified case

    $ curl -I 'http://localhost:40400/bootstrap/css/bootstrap.min.css' -H 'Accept: text/css,*/*;q=0.1' -H 'Cache-Control: max-age=0' -H 'X-DevTools-Emulate-Network-Conditions-Client-Id: A35742C9-1C67-620E-7D73-629A1F5B18B9' -H 'Referer: http://localhost:40400/login' -H 'If-Modified-Since: Tue, 07 Oct 2014 14:36:50 GMT' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.124 Safari/537.36' --compressed

    HTTP/1.1 304 Not Modified
    Set-Cookie: ring-session=f6e2b275-1ccb-41fa-b6b8-1a59994e7426;Path=/
    Set-Cookie: csrftoken=1pYlnSWA7Dmr1S7vBkpdSjNrd0x%2FH91cbpNBaPVfpjFvGEWHUMebCGSQGbaNSnHkqpeGD3VCz6YVsVc%2F;Path=/
    Content-Type: text/css
    Last-Modified: Tue, 07 Oct 2014 14:36:50 GMT
    Content-Length: 101595
    Content-Length: 0
    Server: http-kit
    Date: Tue, 07 Oct 2014 16:09:04 GMT

This breaks. My browser tells me that this response is invalid.

**Comment by ptaoussanis** [comment]
Hi there, could someone please confirm if this issue is resolved / still present as of the [latest http-kit version](https://github.com/http-kit/http-kit/releases)?

Thanks!

**Comment by shenfeng** [comment]
Fixed on `2.1.18`

https://github.com/http-kit/http-kit/blob/master/history.md#2118-2014418
