### ISSUE TITLE
Server feature request: detect when server is done stopping

### ISSUE THREAD

**Issue by tomconnors** [http-kit/http-kit#186]
It appears that stopping the http-kit web server is async, since ThreadPoolExecutor.shutdownNow doesn't wait for active tasks to terminate. Using Stuart Sierra's `component` application architecture and a `reload` function doesn't play well with this asynchrony, since stopping then immediately starting a server throws an error due to the address being in use. Is there any way we could be notified when the server is done listening?

**Comment by venantius** [comment]
I'd like to +1 this - in particular, because I think the docs on the subject are misleading.

Quoth the [docs](http://www.http-kit.org/server.html#options):
```clojure
(defn stop-server []
  (when-not (nil? @server)
    ;; graceful shutdown: wait 100ms for existing requests to be finished
    ;; :timeout is optional, when no timeout, stop immediately
    (@server :timeout 100)
    (reset! server nil)))
```

...in point of fact, omitting the `:timeout` key does nothing to force the server to stop, nor does setting a `:timeout` key of 0. In either case, attempting to restart a server in this fashion results in the rather inconvenient
```
BindException Address already in use  java.net.PlainSocketImpl.socketBind (PlainSocketImpl.java:-2)
```

**Comment by shenfeng** [comment]
should  set `SO_REUSEADDR`?

Here is another solution:

`#'` in `#'chartrootm`   make it  possible not needed to stop the server and restart, for reload purpose.

```clj
(defroutes chartrootm
  (GET "/ws" []  chat-handler)
  (files "" {:root "static"})
  (not-found "<p>Page not found.</p>" ))

(defn- wrap-request-logging [handler]
  (fn [{:keys [request-method uri] :as req}]
    (let [resp (handler req)]
      (info (name request-method) (:status resp)
            (if-let [qs (:query-string req)]
              (str uri "?" qs) uri))
      resp)))

(defn -main [& args]
  (run-server (-> #'chartrootm site wrap-request-logging) {:port 9899})
  (info "server started. http://127.0.0.1:9899"))
```

**Comment by ptaoussanis** [comment]
PR welcome that'd provide a shutdown-complete callback (or `[& synchronous?]` shutdown option).

**Comment by ptaoussanis** [comment]
Will be addressed in next release: `server-stop!` call will now return a promise that you can block on if you like.
