### ISSUE TITLE
Do not exclude Java source files from the JAR

### ISSUE THREAD

**Issue by kumarshantanu** [http-kit/http-kit#189]
As such there is no source JAR for http-kit and the Java source files are not included in the standard JAR, which makes debugging harder. Please either publish a separate source JAR for every release, or do not exclude the Java source files from the standard JAR.

**Comment by ptaoussanis** [comment]
Hi Shantanu, PR would be welcome to mod project.clj to nix the Java source exclusion, thanks!

**Comment by ptaoussanis** [comment]
Hi @kumarshantanu, PR welcome on this - otherwise please feel free to close. Thanks!
