### ISSUE TITLE
http-kit.org out of date; and missing version tag 2.1.18

### ISSUE THREAD

**Issue by favila** [http-kit/http-kit#191]
The github repository is missing a 2.1.18 version tag (latest is 2.1.17).

Also the http-kit.org website is out of date. It says:

>  [http-kit "2.1.16"] ; Add to your project.clj.

Should be 2.1.18

These two issues combined mean it's a little confusing to know which is the current stable version.

**Comment by pandeiro** [comment]
And the latest artifact on Clojars is 2.1.19.

Additionally there are Websocket-related bugfixes (#178) that have been merged already, so a new release would be timely.

**Comment by alexanderkiel** [comment]
Add the currently 70 open issues to the equation and sadly http-kit looks not very healthy right now. I really like the project and use it as server and client.

**Comment by slagyr** [comment]
For lack of better solution, I'm leaning on @pandeiro's release which includes the #178 patch.
[pandeiro/http-kit "2.1.20-SNAPSHOT"]

**Comment by pandeiro** [comment]
@slagyr Yes sorry, I see my fork isn't published anywhere. Oversight on my part. Perhaps we can unite efforts around a new official release that would include #179 as well as more recent patches? What do you think?

**Comment by dpetrovics** [comment]
Any update on a release? Looks like over a year now since the last version on Clojars. It'd be especially great to get #179 out, I'm currently running into that issue.

**Comment by ptaoussanis** [comment]
Have pushed the tag for 2.1.18. Couldn't find info on where 2.1.19's tag should be but that is currently the latest official release.

Otherwise, have started a fork at [com.taoensso.forks/http-kit "2.1.20"] to collect PRs, etc. See https://github.com/http-kit/http-kit/releases for release info.
