### ISSUE TITLE
Hangs when using http streaming channels under load of requests

### ISSUE THREAD

**Issue by michaelr524** [http-kit/http-kit#194]
Maybe related this issue: https://github.com/http-kit/http-kit/issues/76

Even when the handler doesn't do anything but just closes the channel, it looks like all threads are waiting for something.

Tried with latest code from github master branch and also with 2.1.16 and 2.1.19 from clojars.
Is anyone familiar with this problem?

**Comment by ptaoussanis** [comment]
Hi there, busy doing triage - is this still an issue? Is it still reproducible with the [latest release](https://github.com/http-kit/http-kit/releases)?

**Comment by michaelr524** [comment]
Hi Peter, I've replaced httpkit with immuntant ever since so can't really tell..

**Comment by ptaoussanis** [comment]
Great, thanks for the confirmation :-)
