### ISSUE TITLE
How to POST a RAW Message?

### ISSUE THREAD

**Issue by micahasmith** [http-kit/http-kit#197]
I'm converting a FEDEX client from nodejs to clojure and i'm having difficulty matching this line:

https://github.com/PFacheris/packmule/blob/master/lib/fedex/client.js#L72

It seems that neither the `form-params` nor `multipart` match this "raw" style posting of data. 

Can http-kit do this?

**Comment by ddossot** [comment]
What do you mean by "raw"? A plain body entity? In that case, the set this entity as the `:body` key of your request map.

**Comment by micahasmith** [comment]
@ddossot thanks for the quick reply.

`:body` does exactly what i wanted. 

[it isn't represented here](http://www.http-kit.org/client.html#options). is there a place where i can update the documentation for you?
