### ISSUE TITLE
noob here: clojure async channel with with-channel 

### ISSUE THREAD

**Issue by cocodrino** [http-kit/http-kit#198]
Hi..sorry for the noob question, I'm following this response in stackoverflow http://stackoverflow.com/a/24549909

I've this code

```clojure
(defn slow-request []
  (let [chn (!/chan 1)]
    (http/get "http://www.google.com" (fn [resp] (!/put! chn (:body resp))))
    chn))

(defn get-token [  req]
  (with-channel req channl
                (!/go-loop [v (!/<! (slow-request))]
                  (on-close channl (fn [_] (close channl)))
                  (send! channl {:status  200
                                 :headers {"Content-Type" "text/plain"}
                                 :body    (str "response is " v)}))))

```

basically I do an async request and store the result in a channel, then inside with-channel macro I get the result and return it

everything looks fine in the debugger, but unfortunately the body response is not my http request, instead in the browser I've

```html
!!org.httpkit.server.AsyncChannel {closed: false, webSocket: false}
```

I've hear about possible incompatibility between core async and http-kit but I've followed the stackoverflow response and I was curious about how do it...is possible use clojure channels inside the with-channel macro?..what am I doing wrong?..thabk you

**Comment by ptaoussanis** [comment]
Hi there, busy doing issue triage - please feel free to reopen if this issue is still relevant!
