### ISSUE TITLE
vs jetty tradeoffs?

### ISSUE THREAD

**Issue by timvisher** [http-kit/http-kit#199]
I've just spent a few hours scouring the internet looking for docs on why I should use netty/http-kit/async web servers vs. jetty and I've come up with very little. What exactly is the problem with jetty that http-kit was trying to solve? Is there one? Was http-kit more of an exercise for the authors?

I'm sure there are lots of good reasons, but I haven't been able to find them. It would be useful to people like me in the future to have a 'Why use http-kit?' section somewhere that elucidates all this. Failing that, could you respond to this issue with some of the reasons and maybe some key terms I should look up to understand it better?

**Comment by shenfeng** [comment]
I am the main author.  I write http-kit for a project of mine, which need async support.  

Performance, http-kit is slightly faster than jetty. But the bottle neck never comes from the jetty or http-kit. So,  this is not the selling point.

The are 2 reasons, I think, you may want to look at http-kit:

1. http-kit is tiny.  I like tiny things.   Easy to understand.  Use thread more carefully.
2. async api.   long pulling and websocket.

**Comment by timvisher** [comment]
@shenfeng I definitely understand the draw of a small implementation footprint.

Can you elaborate on 2. though? it seems that jetty has full support for websockets and long polling at this point?

**Comment by shenfeng** [comment]
Jetty has websocket and long polling support.  
Not ring-jetty-adapter.    

http-kit exports a non standard async api for Clojure use.

**Comment by timvisher** [comment]
Ah ok. So http-kit is more competing with something like this https://github.com/sunng87/ring-jetty9-adapter that exposes websocket and long polling jetty support?

The default ring-jetty-adapter does not.

If my app does not need websockets or long polling, then perhaps there isn't much to distinguish http-kit from jetty?

**Comment by shenfeng** [comment]
> If my app does not need websockets or long polling, then perhaps there isn't much to distinguish http-kit from jetty?

Yes.   They are interchangeable.
