### ISSUE TITLE
maintenain fixed amount of concurent connections at time

### ISSUE THREAD

**Issue by MikhailKlemin** [http-kit/http-kit#200]
Hello!

Quite often I need to get around 1000+ pages from same server, starting it in async mode probably will lead to get a forbidden response pretty quick if I fire these requests too fast. 

If there any simple, beginner friendly mechanism to keep some fixed amount of concurrent "get"? Like in the Example, assuming the urls - are much larger:

```clojure
(let [urls ["http://server.com/api/1" "http://server.com/api/2"
            "http://server.com/api/3"]
      ;; send the request concurrently (asynchronously)
      futures (doall (map http/get urls))]
  (doseq [resp futures]
    ;; wait for server response synchronously
    (println (-> @resp :opt :url) " status: " (:status @resp))
    )
```
This is especially critical as no proxy is supported in client... 
Please, I am very new to Clojure, and programming as well. I have some experience with Perl.

**Comment by shenfeng** [comment]
Something like `Semaphore` will be helpful.

http://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Semaphore.html
