### ISSUE TITLE
Update docs to clarify when error is returned

### ISSUE THREAD

**Issue by danielcompton** [http-kit/http-kit#203]
Reading the client docs, it wasn't clear that an `error` key is only returned when there is an error in making the request, not when the request returns an error status code e.g. 404 or 500. I think it would be helpful if the docs explained this. I'm happy to put together a PR if the project maintainers agree.

Relates to #175

**Comment by ptaoussanis** [comment]
Sure Daniel, PR welcome!

**Comment by venantius** [comment]
Resolved by #261
