### ISSUE TITLE
Attempt to change on-receive handler causes an exception

### ISSUE THREAD

**Issue by nooga** [http-kit/http-kit#204]
Consider the following case:
```clojure
(defn decide-how-to-handle-messages-in-the-future [data chan]
  (on-receive chan (case (get-kind-of-data data)
                         :a-kind (make-state-bound-handler-fn (make-some-state data chan))
                         :b-kind b-handler-fn
                         etc-handler-fn)))

(defn ws-handler [req]
  (with-channel req chan
    (on-close chan (fn [x] (println "channel closed" x)))
    (on-receive chan (fn [data] (if (initial-message? data) 
                                    (decide-how-to-handle-messages-in-the-future data chan) 
                                    (close chan))))))
```

I get the following exception when `on-receive` is called on `chan` second time:
```
java.lang.IllegalStateException: receive handler exist: foobar.handler$ws_handler$fn__7548@5929a4ed
```
Thrown here: https://github.com/http-kit/http-kit/blob/master/src/java/org/httpkit/server/AsyncChannel.java#L159

Is there a reason why I can't replace current handler fn with another? I imagine it would be useful feature to have.

Is there any way around that?

**Comment by ptaoussanis** [comment]
Hi there,

> Is there a reason why I can't replace current handler fn with another? I imagine it would be useful feature to have.

The handler is established/fixed on first call; i.e. `on-receive` can only be called once and w/in the context of `with-channel`. The handler's just a fn though. You could, for example, have something like:

```clojure
(def my-inner-handler (atom (fn [req])))
(defn my-outer-handler [req] (@my-inner-handler req))
```

Bit of an obtuse example, but hope it illustrates the point. Does that help / make sense?
