### ISSUE TITLE
how to use http-kit client from behind a proxy

### ISSUE THREAD

**Issue by santanuchakrabarti** [http-kit/http-kit#205]
Hi,

I am new to Clojure and http-kit. I like http-kit as I think with http-kit I can develop both a HTTP server and a HTTP client in a very neat way. However I am currently struggling to figure out how can I use http-kit to develop a HTTP client that can be configured to work from behind a HTTP proxy.

Please help me with inputs regarding this. I have checked the documentation http://www.http-kit.org/client.html but found nothing.

Thank and regards
Santanu

**Comment by ptaoussanis** [comment]
Hi there, performing issue triage - is this issue still relevant?
