### ISSUE TITLE
CompilerException java.lang.ClassNotFoundException: clj-http.client

### ISSUE THREAD

**Issue by kindlychung** [http-kit/http-kit#208]
I am getting this error: 

    CompilerException java.lang.ClassNotFoundException: clj-http.client, compiling:(/Users/kaiyin/personal_config_bin_files/workspace/typedclj/src/typedclj/async.clj:12:3) 

Here is the code:

    (ns typedclj.async
      (:require [clojure.core.async
                 :as a
                 :refer [>! <! >!! <!!
                         go chan buffer
                         close! thread
                         alts! alts!! timeout]]))
    
    
    (use 'clojure.pprint)
    (defn blocking-get [url]
      (clj-http.client/get url))

Here is project.clj:

    (defproject typedclj "0.1.0-SNAPSHOT"
      :description "FIXME: write description"
      :url "http://example.com/FIXME"
      :license {:name "Eclipse Public License"
                :url "http://www.eclipse.org/legal/epl-v10.html"}
      :dependencies [[org.clojure/clojure "1.6.0"]
                     [org.clojure/core.async "0.1.346.0-17112a-alpha"]
                     [org.clojure/core.typed "0.2.92"]
                     [clj-http "1.1.2"]
                     [http-kit "2.1.18"]
                     ]
      :main ^:skip-aot typedclj.core
      :target-path "target/%s"
      :profiles {:uberjar {:aot :all}})

**Comment by kindlychung** [comment]
Ah, wrong repo, sorry, please close this.

**Comment by ptaoussanis** [comment]
No problem :-)
