### ISSUE TITLE
Allow the context root to be specified

### ISSUE THREAD

**Issue by yatesco** [http-kit/http-kit#221]
At the moment the app runs at "/", but it would be great if I could configure it so that it ran at "/my-custom-root".

**Comment by rwilson** [comment]
Just stumbled across this comment when looking for something else. You may well already know this, but in case you don't and you're using compojure, just wrap your routes with `(context "/my-custom-root" ... )` and you've got a 1-liner context-root solution.

**Comment by yatesco** [comment]
Thanks Ryan. My mistaken assumption was that the servlet container itself had to know about the context root for proxying.
