### ISSUE TITLE
Client sending any byte after starting a close handshake would cause the WS server to crash

### ISSUE THREAD

**Issue by clyce** [http-kit/http-kit#227]
I used http-kit for websocket server in three different projects, and each of them crashes every 1-3 days (on average load of 10k connections)

The servers' mem usage was stable, but would increase explosively (for about one minute) before crash.

I sampled several heap dumps, which shows: 

![qq 20150826005901](https://cloud.githubusercontent.com/assets/1068472/9473526/d8f16c86-4b8d-11e5-80af-e6534e7ecf9e.jpg)

The toWrite linked list of ServerAtta was holding too many nodes, which draws the mem out.

And EVERTY node on the toWrite linked list was holding the same byteBuffer `[-120 2 3 -24 0 0 0 0 0 0 0 0]`, which could be decoded as Websocket: Close Frame.

----------------------------Updated 2015.08.27-------------------------------

The reason has been found

In method  decodeWS, line 140 `src/java/org/httpkit/server/HttpServer.java`, 

```
                } else if (frame instanceof CloseFrame) {
                    handler.clientClose(atta.channel, ((CloseFrame) frame).getStatus());
                    // close the TCP connection after sent
                    atta.keepalive = false;
                    tryWrite(key, WsEncode(WSDecoder.OPCODE_CLOSE, frame.data));
                }
```

The block of frame CloseFrame was missing a call of `atta.decoder.reset();`, which causes the server to send CLOSE Infinitely when a client send any byte after starting a closing handshake, causing the server to run out of memory.

To prove that, We've written a small priece of code to attack our httpkit websocket server, to send a byte immeidately after requesting the WS Close, and it works, the server went crash after a few seconds.

After we added `atta.decoder.reset()` into the closing block, the attack program doesn't crash the server any more

**Comment by rwilson** [comment]
@clyce If your version of http-kit has been stable since the `atta.decoder.reset()` change, could you submit a PR for that?

**Comment by alolis** [comment]
Very interesting. Your situation looks familiar with what I am experiencing as well. issue#242

**Comment by alolis** [comment]
@clyce ping

**Comment by clyce** [comment]
@alolis Ok I'll check it out~
