### ISSUE TITLE
Issue on connect to https site with TLS 1.2 suport

### ISSUE THREAD

**Issue by Tirex** [http-kit/http-kit#228]
Can't connect to https://3dsecure.kkb.kz. It's support only TLS 1.2.
Got error: SSLException javax.net.ssl.SSLException: Received fatal alert: protocol_version
Trying on Java 7, OpenSSL 1.0.1g 7 Apr 2014

**Comment by pgdad** [comment]
(defonce ssl-engine
  (let [tm (reify javax.net.ssl.X509TrustManager
             (getAcceptedIssuers [this]
                                 (make-array X509Certificate 0))
             (checkClientTrusted [this chain auth-type])
             (checkServerTrusted [this chain auth-type]))
        client-context (SSLContext/getInstance "TLSv1.2")]
    (.init client-context nil (-> (make-array TrustManager 1) (doto (aset 0 tm))) nil)
    (.createSSLEngine client-context)))

Then:

(http/get <your url> {:sslengine ssl-engine})

where http/get is result of requiring http-kit client, obviously bunch of imports for related java classes are also required

**Comment by marklar** [comment]
The Markdown (without coding backticks) messed up the text of pgdad's comment.
Can anyone provide the code in its proper format?
Thanks!

**Comment by marklar** [comment]
I think it may be this (w/ imports added)...

```clojure
(ns my.namespace
  (:import (javax.net.ssl X509TrustManager SSLContext TrustManager)
           (java.security.cert X509Certificate)))

(defonce ssl-engine
  (let [tm (reify javax.net.ssl.X509TrustManager
             (getAcceptedIssuers [this] (make-array X509Certificate 0))
             (checkClientTrusted [this chain auth-type])
             (checkServerTrusted [this chain auth-type]))
        client-context (SSLContext/getInstance "TLSv1.2")]
    (.init client-context nil
           (-> (make-array TrustManager 1)
               (doto (aset 0 tm)))
           nil)
    (.createSSLEngine client-context)))
```

Does that look right? Thanks!

**Comment by ptaoussanis** [comment]
Hi there, performing issue triage - is this issue still relevant?

**Comment by marklar** [comment]
I've found that moving from Java 1.7 to 1.8 made this problem go away.
Thanks.

**Comment by ptaoussanis** [comment]
Great, thanks for the update - may come in handy for others :-)

**Comment by kendagriff** [comment]
@marklar's suggestion worked great for us in transitioning from 1.0 to 1.2.
