### ISSUE TITLE
Server feature request: threadpool access

### ISSUE THREAD

**Issue by msassak** [http-kit/http-kit#231]
I'm using httpkit in production (it works great, thanks!) and would like to monitor the server threadpool via JMX. Unfortunately I can't figure out a way to get access to that pool without patching httpkit, but before I start writing a patch I wanted to ask in case I missed something obvious. If it turns out there's no good way to get at the pool with the current code, I think it could be exposed in a few different ways:

1. Allow the user to pass RingHandler (or the thread pool proper) into `server/run-server`.
1. Add a getter to RingHandler exposing the `execs` thread pool and add the Ring handler to the stop-server metadata alongside the server.

I prefer the second option, because it seems less intrusive, although it is less flexible. Is there a better way to do this, or should I start working on a patch?

**Comment by mhjort** [comment]
I think passing in Threadpool implementation would work well (option 1). http-kit client already accepts :worker-pool parameter for passing in your own Executor. So server could work in similar way.

**Comment by ptaoussanis** [comment]
@msassak Hi Mike, PR welcome for implementing this as per @mhjort's suggestion - thanks!

**Comment by ptaoussanis** [comment]
This issue's getting quite old. Final call for PRs before closing?

**Comment by msassak** [comment]
It would be useful, but I unfortunately don't have the time to implement it myself right now.

**Comment by kaibra** [comment]
Had the same issue. My plan was to have some graphite-metrics running for current active threads + queue size.
What do you think about #307

**Comment by ptaoussanis** [comment]
Closing as resolved with the patch provided by @kaibra (thanks!)
