### ISSUE TITLE
Server can't send back any response.

### ISSUE THREAD

**Issue by songsd** [http-kit/http-kit#232]
I'm using http-kit to provide rpc services and  websocket service.When running after some time,the server can't work.I am using telnet to connect the port,the server can establish connection,but can't send back any response.There is nothing special in the log file.If using brower to open the url,it will be waiting forever.

Connected to 10.10.2.221.
Escape character is '^]'.
^]
telnet> 
alsdfk

asdklfjasdfsdf

sadf
asdfasd
fa
sdf
as
dfasd
fa
sdf
a
sdf
a

**Comment by songsd** [comment]
Got the reason:OutofMemoryError.

If I create a connection to the server and doesn't send anything via it,the connection will be kept forever.
Many server can close the connection when some seconds passed.

**Comment by ptaoussanis** [comment]
Hi there, performing issue triage - can this be closed?
