### ISSUE TITLE
Catch Throwable when delivering response

### ISSUE THREAD

**Issue by msassak** [http-kit/http-kit#235]
The deliver-resp helper function in org.httpkit.client/request catches Exception, but not Throwable. Any code in the callback that throws Throwable rather than Exception prevents the client thread from ever returning (so far as I can tell). That is unfortunate, because Clojure's assert, and :pre and :post conditions all throw Throwable rather than Exception, leading to some very hard to troubleshoot failures.

[PR here](https://github.com/http-kit/http-kit/pull/234)

**Comment by cassc** [comment]
You can wrap your ring handlers with a catch-all throwable function, e.g., with lib-noir, add the following function as a middleware,

```clojure
(defn wrap-catch-throwable [handler]
  (fn [req]
    (try
      (handler req)
      (catch Throwable e
        ;; handle or log error
        (noir.response/status 500 (.getMessage e))))))

(run-server (->
             (noir.util.middleware/app-handler
              [your-routes]
              :middleware [wrap-catch-throwable])))
```

**Comment by msassak** [comment]
I do that. This is a separate issue.

**Comment by msassak** [comment]
Sorry hit comment too soon. This is a separate issue. The throwable will not be returned from httpkit.client/request, so the middleware does not have a chance to catch it. Try this is a repl:

```
(require '[org.httpkit.client :as client])
@(client/get "http://www.google.com (fn [_] (throw (Throwable. "hi"))))
```

When I do that (and the tests for the PR do this for me, too), the Throwable is never delivered to the promise.

**Comment by ptaoussanis** [comment]
This is now addressed in `[com.taoensso.forks/http-kit "2.1.20"]`, thanks!
