### ISSUE TITLE
Client feature request: add performance metrics for requests

### ISSUE THREAD

**Issue by spiffytech** [http-kit/http-kit#240]
I'm using http-kit's client library to measure the performance of my website. Right now I'm measuring timestamps before and after my asynchronous HTTP query, but I wouldn't be surprised if my results are off by several milliseconds as I can't take into account http-kit's overhead before/after making the network call.

It would be nice if http-kit could supply to the callback the number of milliseconds a response took, measured as closely to the network layer as possible.

**Comment by ptaoussanis** [comment]
Closing as stale, please feel free to reopen if you'd like to submit a PR - thanks! :-)
