### ISSUE TITLE
Odd behavior with Apache proxy

### ISSUE THREAD

**Issue by giorgio-v** [http-kit/http-kit#241]
I’m trying to setup an Apache proxy in front of a web app that uses [Sente](https://github.com/ptaoussanis/sente). (I’m posting an issue here because the exact same Apache configuration works flawlessly with different, non-Clojure, application).

Basically, the problem is that it seems that the web socket is open after, say, a minute or so. Here is the screenshot of the browser console messages 

![schermata 2015-12-02 alle 14 31 46](https://cloud.githubusercontent.com/assets/551484/11532241/e02b51a2-9902-11e5-8e7b-7e7be6e26f04.png)

and these are the log messages on the backend, from Apache error log:
```
[Wed Dec 02 13:25:04.915283 2015] [proxy_http:error] [pid 41105] (70007)The timeout specified has expired: [client 192.168.38.1:49952] AH01102: error reading status line from remote server 127.0.0.1:3000
[Wed Dec 02 13:25:04.915424 2015] [proxy:error] [pid 41105] [client 192.168.38.1:49952] AH00898: Error reading from remote server returned by /chsk
[Wed Dec 02 13:26:07.505470 2015] [proxy_http:error] [pid 41108] (70007)The timeout specified has expired: [client 192.168.38.1:49969] AH01102: error reading status line from remote server 127.0.0.1:3000
[Wed Dec 02 13:26:07.505630 2015] [proxy:error] [pid 41108] [client 192.168.38.1:49969] AH00898: Error reading from remote server returned by /chsk
```

and from the clojure app:
```
Wed Dec 02 13:24:00 UTC 2015 [server-loop] WARN - unmasked client to server frame
15-Dec-02 13:24:04 localhost DEBUG [aim.api] - Unhandled event: :chsk/uidport-open
15-Dec-02 13:26:11 localhost DEBUG [aim.api] - :aim.data/send-diff, session ID 6a5d882a-792a-429a-8865-189700ba5877
```

Any thoughts on this?

**Comment by giorgio-v** [comment]
I get the same behavior with Nginx. In fact, it is even worse: Sente keeps trying to reconnect.

**Comment by ptaoussanis** [comment]
Hi Giorgio, think this is probably better followed up on Sente's end - will close this and reply at https://github.com/ptaoussanis/sente/issues/183 in a moment
