### ISSUE TITLE
Application exit with "killed" message

### ISSUE THREAD

**Issue by alolis** [http-kit/http-kit#242]
Hello,

I have implemented an application that servers data via websockets with the use of http-kit and I have noticed the following and I am trying to understand what is going on. The application runs normally for 24hrs - 48hrs and then it either:
- Continues to run but it no longer is able to accept new connections 
- Exits with console message "killed"

I use core.async channels in my application and in general it's a very simple one but I am having trouble understanding where the problem might be. Is there a way to enable debug messages for http-kit? When does the "killed" message happens? What went wrong?

Thank you for your time

**Comment by alolis** [comment]
I also see the following warning:

`[server-loop] WARN - not impl for opcode: 10`

**Comment by rwilson** [comment]
Could this be related to #227?

**Comment by alolis** [comment]
I think #227 looks more related with mine than #194 but of course, i cant be sure. If a PR is submitted for #227 I would be more than happy to test and report.

**Comment by ptaoussanis** [comment]
Hi Alexander,

Could you possibly try confirm whether this issue still exists with `[http-kit "2.2.21-alpha2"]`?

**Comment by alolis** [comment]
@ptaoussanis I keep bump into you everywhere :) I will download asap and re-test everything.

**Comment by ptaoussanis** [comment]
@alolis Clearly I need a hobby ;-)

**Comment by alolis** [comment]
@ptaoussanis is the version correct? [http-kit "2.2.21-alpha2"] I am having trouble including it in the project. I even tried to git clone the project but it seems that it installs [http-kit "2.**1**.21-alpha2"]

**Comment by ptaoussanis** [comment]
`[http-kit "2.1.21-alpha2"]` is correct, sorry- typo! Will fix now.

**Comment by alolis** [comment]
@ptaoussanis , it seems that the latest dev didn't help. I will try the suggestion in #227

**Comment by ptaoussanis** [comment]
Okay great, thank you for confirming!

**Comment by nberger** [comment]
Perhaps related to http://www.evanjones.ca/java-bytebuffer-leak.html? http-kit uses Java NIO and ByteBuffers...

It'd be great if you can confirm whether the app is killed because of running out of memory

**Comment by alolis** [comment]
@nberger , any suggestions on how to make that confirmation? The machine seems to be running normally in general, with plenty of RAM.

**Comment by nberger** [comment]
The answers to this SO question should help in getting that confirmation:
http://stackoverflow.com/questions/726690/who-killed-my-process-and-why

**Comment by alolis** [comment]
@nberger , it looks like it is an "out of memory" issue if i judge from what `dmesg` shows.

@ptaoussanis , i tried the recommendation from #227 by applying it to `[http-kit "2.1.21-alpha2"]` but the results are the same. Application crashes after some hours of operation. I bumped on you, once again, when i started looking for alternatives and found [sente](https://github.com/ptaoussanis/sente). I haven't tried it yet but I am definitely going to make the switch and give it a go because http-kit and websockets simply don't want to work properly.

**Comment by venantius** [comment]
@alolis - two questions. One, are you still getting the `not impl for opcode` message? I find that one particularly strange since it should never happen (error is thrown by `default` at https://github.com/http-kit/http-kit/blob/master/src/java/org/httpkit/server/WSDecoder.java#L165, but the value of OPCODE_PONG is 10 at https://github.com/http-kit/http-kit/blob/master/src/java/org/httpkit/server/WSDecoder.java#L160). I can't explain what's happening there. 

Two, I suspect there's a chance that the problem you're describing of running out of memory may be solved by #258, since that PR addressed a case where http-kit would append infinitely to a ConcurrentLinkedList without pulling.

**Comment by venantius** [comment]
**follow-up to two: could you pull down the latest on master, install it and see if your problem is still persisting?

**Comment by venantius** [comment]
If your problem persists on master, I'd also be curious as to whether the fix proposed in #259 resolves this for you.

**Comment by alolis** [comment]
@venantius , my apologies for the delayed reply, I didn't reply there was an update on the issue. Just got the master and updated my app. I will let you know what will happen.

Regarding your question with `no impl for opcode` I was no longer seeing this message after I upgraded to a newer version couple of months ago, just the `killed` message.

**Comment by venantius** [comment]
Okay, well that puts my mind at ease! :)

Please check back in with us in ~72 hours if you haven't encountered this bug again and we'll mark this ticket as closed.

**Comment by alolis** [comment]
@venantius , crash again I am afraid, with message `Killed` after 24hrs of normal operation.

**Comment by ptaoussanis** [comment]
> [server-loop] WARN - not impl for opcode: 10

@alolis Do you still see this warning? Could you possibly give any more detail re: where/when you see it?

**Comment by alolis** [comment]
@ptaoussanis , I haven't seen it for some time now after our last chat. I now only see the killed message. I re-started the app to see if I will see a different message or just the `Killed`

**Comment by alolis** [comment]
@ptaoussanis @venantius I now see a new message just before the `Killed`

````
ERROR reactor.core.Reactor -
java.lang.NullPointerException
````
Not sure if it helps

**Comment by venantius** [comment]
Could you capture the full stacktrace there, either by running your server at the repl and calling (pst) after the NPE or otherwise attempting to handle the error and get us a full trace?

**Comment by venantius** [comment]
(Ping!)

**Comment by alolis** [comment]
@venantius , my apologies, I was dealing with some personal matters. I will do the test and get back to you.

**Comment by ptaoussanis** [comment]
Requesting for an update on this issue? Thanks!

**Comment by alolis** [comment]
@ptaoussanis , my apologies for the long long delay. I had my reasons which I do not want to bother you about :)

I have updated the project to use the latest `2.2.0` version and re-running everything fresh. If it crashes again I will do what @venantius suggested to capture the full stacktrace.

**Comment by ptaoussanis** [comment]
No problem @alolis, thanks. Any update so far? Please feel free to close if it looks like the problem is resolved.

**Comment by alolis** [comment]
@ptaoussanis , It seems that the problem persists. I will setup dev version on the machine and get that stacktrace.

**Comment by ptaoussanis** [comment]
Thanks, much appreciated!

**Comment by ptaoussanis** [comment]
Closing as part of issue triage due to inactivity. Please feel free to re-open if this is still relevant.
