### ISSUE TITLE
Client: StackOverflow when deref'ing a timeout-promise

### ISSUE THREAD

**Issue by the-kenny** [http-kit/http-kit#246]
`(http/get "http://google.de" {:timeout 1})` sometimes throws my REPL into an endless recursion:

```
1. Unhandled java.lang.StackOverflowError
   (No message)

                core_print.clj:  389  clojure.core/deref-as-map
                core_print.clj:  411  clojure.core/fn
                  MultiFn.java:  233  clojure.lang.MultiFn/invoke
                      core.clj: 3548  clojure.core/pr-on
                core_print.clj:  212  clojure.core/print-map/fn
                core_print.clj:   59  clojure.core/print-sequential
                core_print.clj:  209  clojure.core/print-map
                core_print.clj:  219  clojure.core/fn
                  MultiFn.java:  233  clojure.lang.MultiFn/invoke
                      core.clj: 3548  clojure.core/pr-on
```

This is caused by the result of the promise containing the promise itself, and as the print-representation of a delivered promise contains its value, it throws the printer in an endless loop:

```
(let [pro (http/get "http://google.de" {:timeout 1})]
  (= pro (-> @pro :opts :response)))
;; => true
```

**Comment by mhjort** [comment]
What version are you using. For me this:

`(let [pro (http/get "http://google.de" {:timeout 1})]
   (= pro (-> @pro :opts :response)))`


returns false

**Comment by the-kenny** [comment]
Could you try again with `https://httpbin.org/delay/3` as the url? This url waits 3 seconds before serving the response, assuring the timeout-exception is thrown. 

My colleague and me are still able to reproduce this on `[com.taoensso.forks/http-kit "2.1.20"]` and before.

**Comment by ptaoussanis** [comment]
Requesting confirmation if this is still an issue with `[http-kit "2.2.0"]`. If it is, open to a PR. Thanks!

**Comment by javahippie** [comment]
Trying to reproduce with following code in version 2.2.0:

```
(let [pro (http/get "https://httpbin.org/delay/3" {:timeout 1})] 
    (= pro (-> @pro :opts :response)))
```

Always returns true with no exception to me.

**Comment by ptaoussanis** [comment]
Thank you @javahippie, will assume this is resolved. If someone is still running into this with >= v2.2.0, please feel free to reopen.

**Comment by deckeraa** [comment]
I believe I have repro'd this issue.

```
> (def example @(http/get "http://crates.io/api/v1/crates/rand/0.8.5/download"))
> (keys example)
(:opts :error)
> (keys @(-> example :opts :response))
(:opts :error)
```

`(println example)` truncates output at 1MB. The promise occurs to be recursive

Something interesting is that `(:error example)` contains:
```
(:error example)
#error {
 :cause "Unrecognized record version (D)TLS-0.0 , plaintext connection?"
 :via
 [{:type javax.net.ssl.SSLException
   :message "Unrecognized record version (D)TLS-0.0 , plaintext connection?"
   :at [sun.security.ssl.SSLEngineInputRecord bytesInCompletePacket "SSLEngineInputRecord.java" 98]}]
 :trace
 [[sun.security.ssl.SSLEngineInputRecord bytesInCompletePacket "SSLEngineInputRecord.java" 98]
  [sun.security.ssl.SSLEngineInputRecord bytesInCompletePacket "SSLEngineInputRecord.java" 64]
  [sun.security.ssl.SSLEngineImpl readRecord "SSLEngineImpl.java" 557]
  [sun.security.ssl.SSLEngineImpl unwrap "SSLEngineImpl.java" 454]
  [sun.security.ssl.SSLEngineImpl unwrap "SSLEngineImpl.java" 433]
  [javax.net.ssl.SSLEngine unwrap "SSLEngine.java" 637]
  [org.httpkit.client.HttpsRequest doHandshake "HttpsRequest.java" 98]
  [org.httpkit.client.HttpClient doRead "HttpClient.java" 193]
  [org.httpkit.client.HttpClient run "HttpClient.java" 494]
  [java.lang.Thread run "Thread.java" 829]]}
```

A search for an issue involving "(D)TLS-0.0" yields https://github.com/cognitect-labs/aws-api/issues/139 but that appears to have ended inconclusively.

**Comment by ptaoussanis** [comment]
@deckeraa Thanks for the info.

Could you please try with the latest version of http-kit (2.6.0) and with the SNI client?:

```clojure
(require '[org.httpkit.sni-client :as sni-client])
(alter-var-root #'org.httpkit.client/*default-client* (fn [_] sni-client/default-client))
```

**Comment by deckeraa** [comment]
Update: Enabling SNI via https://github.com/http-kit/http-kit#enabling-client-sni-support-disabled-by-default resolves the repro'd case above. My hypothesis is that No SNI -> SSL fails -> some strange codepath that leads to recursive errors.
