### ISSUE TITLE
Custom response for "entity too large" exceptions?

### ISSUE THREAD

**Issue by skazhy** [http-kit/http-kit#253]
If request results in HTTP 413, a [preset message](https://github.com/http-kit/http-kit/blob/master/src/java/org/httpkit/server/HttpDecoder.java#L304-L309) is sent to the client. It would be nice to customize this.

**Comment by ptaoussanis** [comment]
Hi Kārlis, sure - PR welcome!

**Comment by ptaoussanis** [comment]
Closing as stale, please feel free to reopen if you'd like to submit a PR - thanks! :-)
