### ISSUE TITLE
Cutting a new release

### ISSUE THREAD

**Issue by ptaoussanis** [http-kit/http-kit#268]
@venantius @mhjort Hi there, are there any specific uncommitted changes either of you would still like to see included in the next release?

Otherwise please let me know if I've got your go-ahead to cut the next alpha.

The Travis build remains a bit fragile but I've been unable to reproduce any test failures locally. Not familiar enough with Travis to say whether this seems unusual or not (?). Anyway, doesn't appear that the CI failures have anything to do with changes from the last tagged release so I'd be okay to not block on this.

Thanks-

**Comment by venantius** [comment]
I've been thinking it's time to cut a new release. 

I wouldn't worry about Travis; it seems that we're getting a lot of timeout and ordering failures but, as you say, nothing we can reproduce locally. I'd argue we should move those tests out of the travis test-selector group and/or build some benchmarking stats that we run in travis instead (just so we can keep an eye on whether the timeout stats get better or worse).

:+1: to cutting a new alpha.

**Comment by mhjort** [comment]
Yep. I think the biggest challenge with Travis is that machines are just a lot slower than our local machines. That often leads into problems with asynchronous tests. 

+1 for the new release.

**Comment by ptaoussanis** [comment]
Great, `2.2.0-alpha1` is out - release info at: https://github.com/http-kit/http-kit/releases

@venantius Please note that you'll want to rebase again for any future work. If there's demand, we can switch to a dev branch for transient work on future releases.

Big thanks to both of you (and the other contributors) for making this release happen! :+1: :-)
