### ISSUE TITLE
Question: How to use http/request with client certificates?

### ISSUE THREAD

**Issue by urzds** [http-kit/http-kit#276]
I am searching for a Clojure HTTP client library that supports client certificates. Does http-kit support these? How do I access that functionality?

I looked at the [client docs](http://www.http-kit.org/client.html#options) but could not find this information.

**Comment by venantius** [comment]
Hey @urzds - I'd recommend checking out the example from `less-awful-ssl` which tells you how to do this https://github.com/aphyr/less-awful-ssl#example
