### ISSUE TITLE
Using local aliases in /etc/hosts throws UnknownHostException

### ISSUE THREAD

**Issue by bramkoot** [http-kit/http-kit#277]
I run into trouble while using a local host alias in my /etc/hosts file. I run another http-service in docker and I have a specific alias for my docker-ip. While using the alias, I get an `java.net.UnknownHostException.`

The complete error, the host is called `central-system:`
```
[{:type java.net.UnknownHostException
    :message central-system: unknown error
    :at [java.net.Inet6AddressImpl lookupAllHostAddr Inet6AddressImpl.java -2]}]
  :trace
  [[java.net.Inet6AddressImpl lookupAllHostAddr Inet6AddressImpl.java -2]
   [java.net.InetAddress$2 lookupAllHostAddr InetAddress.java 907]
   [java.net.InetAddress getAddressesFromNameService InetAddress.java 1302]
   [java.net.InetAddress getAllByName0 InetAddress.java 1255]
   [java.net.InetAddress getAllByName InetAddress.java 1171]
   [java.net.InetAddress getAllByName InetAddress.java 1105]
   [java.net.InetAddress getByName InetAddress.java 1055]
   [org.httpkit.HttpUtils getServerAddr HttpUtils.java 253]
   [org.httpkit.client.HttpClient exec HttpClient.java 237]
```

I tried exactly the same code with:
- localhost -> works (put port is not responding)
- google.nl -> works (but 404 :-)
- the actual docker ip -> works perfectly
- using other hostnames which look more like normal domains, like central-system.nl, still does not work

Any idea's why http-kit is not picking up the local alias?

**Comment by venantius** [comment]
Is this just within Docker? If so, I suspect this is one of a larger class of `/etc/hosts` issues that are known to be Docker bugs.

**Comment by bramkoot** [comment]
Sorry for that - was indeed a docker issue. Fixed now.

**Comment by oblodgett** [comment]
Can you elaborate on the "Is this just within Docker? If so, I suspect this is one of a larger class of /etc/hosts issues that are known to be Docker bugs." or point me to something that I can read about these?
