### ISSUE TITLE
Support for http2

### ISSUE THREAD

**Issue by MichaelStephan** [http-kit/http-kit#278]
Hello,

I would like to ask if you plan to support http2 in the near future.

Thanks for the information.

**Comment by hamidr** [comment]
:+1:

**Comment by ptaoussanis** [comment]
Hi there, this is very unlikely. The usual recommendation is that you run http-kit behind something like nginx for security, static files, etc. You can also use it (or a similar gateway) to get http/2 support.

Best of luck!

**Comment by MichaelStephan** [comment]
Hello @ptaoussanis, thanks for your answer. I followed your approach and it works nicely.

**Comment by ptaoussanis** [comment]
No problem, thanks for the confirmation!
