### ISSUE TITLE
New proxy functionality does not handle https properly.

### ISSUE THREAD

**Issue by jbristow** [http-kit/http-kit#280]
I noticed that the new proxy functionality causes some issues when it tries to call the http proxy with a https request.

`{:opts {:url "https://www.google.com", :method :get, :proxy "http://127.0.0.1:8181"}, :error #<ProtocolException org.httpkit.ProtocolException: No status>}`

I have a PR ready that I think will fix this, but I need some eyes on it to a) figure out if I actually solved the problem and b) make sure I'm testing this right.

**Comment by jbristow** [comment]
The main problem I saw is that when you connect to an http proxy with http-kit, (say it's on my-proxy:80) and then try to connect to https://www.google.com, the request is still marked as https, so this code fails:


```java
// src/java/org/httpkit/client/HttpsRequest.java lines 135-141
    public void recycle(Request old) throws SSLException {
        super.recycle(old);
        this.engine = ((HttpsRequest) old).engine;
        this.handshaken = true;
        wrapRequest(); // prepare for write
    }
```
because the request is a `Request` object and cannot be cast.

**Comment by jbristow** [comment]
It's difficult for me to diagnose exactly because I'm still spinning up on all the mechanics of what's going on in an http request when I do something like this:

```bash
https_proxy="http://localhost:8181s" curl -v -k https://www.google.com/
```

**Comment by jshaw86** [comment]
Was just wondering if there was an update on this? If I can be of help let me know.

**Comment by jbristow** [comment]
@jshaw86 Can you look at [my PR](https://github.com/http-kit/http-kit/pull/281) and see if I'm on the right track?  I'm used to dealing with an apache.httpclient level of abstraction, so this is a little closer to the bone than I'm comfortable with.

**Comment by jbristow** [comment]
Also, looking at the proxies I'm dealing with, it looks like they don't advertise that they're on https at all, they just handle both transparently.

**Comment by jshaw86** [comment]
@jbristow I wanted to make sure I understood the fundamental issue. The way I see it is if we made a https from client -> proxy server that would not be respected without the pull request?

If that's correct then I'll just more or less run the tests and do a sanity check, the if condition though seems reasonable.

**Comment by jbristow** [comment]
Right, when I connect to my egress proxies  using clj-http, I connect via "host:port", and the connection goes through whether I hit `http://www.google.com` or `https://www.google.com`.

**Comment by jshaw86** [comment]
@jbristow so your specific changes look fine. I'm not too sure though if it will actually fix the issue with HTTPS. After applying your fix to my branch I still wasn't able to HTTPS out through my outbound proxy (using squid proxy). I think what may need to be done is more or less what's outlined in this SO: http://stackoverflow.com/questions/11697943/when-should-one-use-connect-and-get-http-methods-at-http-proxy-server

I've also attached some tcpdump first using curl (successful HTTPS through proxy) and using http-kit (non-successful through proxy) to see the actual wire difference. Thoughts?
[curl-3128.txt](https://github.com/http-kit/http-kit/files/253321/curl-3128.txt)
[http-kit-3128.txt](https://github.com/http-kit/http-kit/files/253322/http-kit-3128.txt)

**Comment by jshaw86** [comment]
I want to do a little more testing but I got this working by leveraging CONNECT tunneling: https://github.com/pubnub/http-kit/commit/3666efc98c30bb6f427c0388b278729a972cf4a9.

Let me know thoughts.

**Comment by jshaw86** [comment]
@jbristow here's my pull request combining your work and mine: #291.

**Comment by ptaoussanis** [comment]
Merged, thanks!

**Comment by ptaoussanis** [comment]
Closing with #291
