### ISSUE TITLE
Possible websocket feature request: on-open action for websocket connection(with-channel)

### ISSUE THREAD

**Issue by hamidr** [http-kit/http-kit#285]
I think it's kind necessary to able to distinguish when a websocket connection is about to be made( to get upgraded).

My need is when I'm opening a connection I need to authenticate first and then approve it as a new connection;
By this scenario I saw that in this line 
https://github.com/http-kit/http-kit/blob/master/src/org/httpkit/server.clj#L165 
the websocket gets upgraded without any callback or some interface for user to approve the "connect" action Or I might be completely wrong.
1. try to connect to the server with url: foo.bar/ws?user=foo1&pass=bar1
2. if authenticated connection gets opened(upgraded to websocket connection) and if not it gets rejected by the server.
I dont want an open connection and then authenticating the connection and then close it if I want.
If the need that I described is valid then I would like to contribute and send a PR myself for this feature.
Thank you.

**Comment by zentrope** [comment]
You can do this with middleware by inspecting the headers for "upgrade". My problem is that I have no way to return sec-websocket-protocol headers. Chrome breaks.

**Comment by ptaoussanis** [comment]
Hi, thanks for bringing this up. Have split some of `with-channel`'s logic out into smaller components to let you manually handle if/when to upgrade WebSocket requests.
