### ISSUE TITLE
Undeterministic behaviour for larger POSTs when :max-body is set

### ISSUE THREAD

**Issue by moohdyy** [http-kit/http-kit#288]
Hello everyone, 

I am unsure if this problem is related to #90 because this concern is about the request an not the response.

## problem decription
I am trying to set a limitation for the POST request length with help of the :max-body parameter.
Up to a certain length (~50000 characters), the expected error-message is returned, but with increasing length of the body, sometimes (!) no answer is received at all. 
The longer the body, the more often you do not receive an answer (a body length of ~250000 characters returns as expected in only 5% of the POSTs)

## minimal code example:
project.clj:
```Clojure
(defproject httpkit-test "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[compojure "1.5.0"]
                 [org.clojure/clojure "1.7.0"]
                 [http-kit "2.1.19"]]
  :repl-options {:init-ns httpkit-test.core})

```
httpkit-test.core
```Clojure
(ns httpkit-test.core
  (:require [org.httpkit.server :refer :all]
            [compojure.core :refer [defroutes POST]]))

(defroutes app
           (POST "/process" [] {:status 200 :body "OK!"}))

(defonce server (atom nil))

(defn start []
  (reset! server (run-server #'app {:port 8091 :max-body 10})))

(defn stop []
  (@server))
```
## reproducing the behaviour
with help of the "postman chrome app", I send a POST request to " 127.0.0.1:8091/process"
with raw text as input. 
I initialised the http-kit server with :max-body 10, and small text inputs work as expected:
 "1234567890" returns  "OK!"  and 
 "12345678901" returns "request body 11; max request body 10"

but, when I POST a long text like the one I uploaded (_test.txt_) , postman does sometimes receive the correct answer ("request body 231255; max request body 10"), but in 95% of time, it does not receive a response at all.

## remarks
When removing the :max-body parameter, the large body passes and returns "OK".
I debugged in the http-kit code and the difference between the two behaviours shows in the method **try-write** of **HttpServer.java** (I commented in the relevant line)
```Java
public void tryWrite(final SelectionKey key, boolean chunkInprogress, ByteBuffer... buffers) {
        ServerAtta atta = (ServerAtta) key.attachment();
        synchronized (atta) {
            atta.chunkedResponseInprogress(chunkInprogress);
            if (atta.toWrites.isEmpty()) {
                SocketChannel ch = (SocketChannel) key.channel();
                try {
                    ch.write(buffers, 0, buffers.length); // Here, the response with the RequestTooLargeException is written in correct cases. In faulty cases, nothing happens here.
                    if (buffers[buffers.length - 1].hasRemaining()) {
                        for (ByteBuffer b : buffers) {
                            if (b.hasRemaining()) {
                                atta.toWrites.add(b);
                            }
                        }
                        pending.add(new PendingKey(key, PendingKey.OP_WRITE));
                        selector.wakeup();
                    } else if (!atta.isKeepAlive()) {
                        pending.add(new PendingKey(key, CLOSE_NORMAL));
                    }
                } catch (IOException e) {
                    pending.add(new PendingKey(key, CLOSE_AWAY));
                }
            } else {
                Collections.addAll(atta.toWrites, buffers);
                pending.add(new PendingKey(key, PendingKey.OP_WRITE));
                selector.wakeup();
            }
        }
    }
```
In both cases, the RequestTooLargeException is thrown and stored in the _buffers_ variable.

[test.txt](https://github.com/http-kit/http-kit/files/240442/test.txt)

**Comment by javahippie** [comment]
I tried to reproduce this issue, unfortunately I was not able to see your error.

My system configuration:
*CIDER 0.8.1 (package: 20141120.1746) (Java 1.8.0_25, Clojure 1.7.0, nREPL 0.2.6)
* OSX 10.11.5

Was is your exact configuration?

I used your provided code and the Postman Mac App and the HTTP code '413 - Request Entity too large' was returned 100% of the time with following message:
`request body 231255; max request body 10`

I added my showcase/playground app to my repository, maybe this helps while trying to reproduce the behaviour: https://github.com/javahippie/http-kit-288

**Comment by moohdyy** [comment]
@javahippie 

I verified that the problem persists in your showcase on my setup.
I checked out your showcase and added a main function (see PR) to eliminate my IDE as a cause.

Running the program with "lein run" still produces the same behaviour.

My system configuration:
Windows 10 | Version 1511 | Build 10584.420
Leiningen 2.5.3 on Java 1.8.0_77 Java HotSpot(TM) 64-Bit Server VM

**Comment by moohdyy** [comment]
I found the culprit in this scenario:
When I used a simple curl POST, everything worked as expected, even with much bigger files.
So it must be a bug within my **postman app** (current version):

Postman 4.4.2
win / x86-32
Chrome 51.0.2704.103

Thank you for your investigation, so everything is fine with http-kit :+1:
