### ISSUE TITLE
How to overcome latency degradation on many concurrent requests?

### ISSUE THREAD

**Issue by dfdx** [http-kit/http-kit#295]
Using example from the main page:

```
(defn async-handler [ring-request]
  ;; unified API for WebSocket and HTTP long polling/streaming
  (with-channel ring-request channel    ; get the channel
    (if (websocket? channel)            ; if you want to distinguish them
      (on-receive channel (fn [data]     ; two way communication
                            (send! channel data)))
      (send! channel {:status 200
                      :headers {"Content-Type" "text/plain"}
                      :body    "Long polling?"}))))

(run-server async-handler {:port 8080}) ; Ring server
```
and ApacheBench with non-keepalive connections we get the following results for latencies: 

```
$ ab -n 100000 -c 100 http://127.0.0.1:8080/
...
Percentage of the requests served within a certain time (ms)
  50%      4
  66%      4
  75%      4
  80%      4
  90%      5
  95%      5
  98%      5
  99%      6
 100%   1005 (longest request)

$ ab -n 100000 -c 1000 http://127.0.0.1:8080/
...
Percentage of the requests served within a certain time (ms)
  50%     26
  66%     32
  75%     34
  80%     35
  90%     44
  95%     49
  98%     70
  99%   1023
 100%   1037 (longest request)

$ ab -n 100000 -c 10000 http://127.0.0.1:8080/
...
Percentage of the requests served within a certain time (ms)
  50%    346
  66%    373
  75%    395
  80%    433
  90%   1229
  95%   1375
  98%   1658
  99%   3371
 100%   4836 (longest request)
```
So latencies grow linearly. However, I don't see why it should happen - total CPU usage over 80 cores is below 20%, JVM is started with `-Xms30G -Xmx30G` so memory is not a problem and network load is tiny. 

What is limiting latency in this case? And more importantly, can we improve it? 

Thanks in advance

**Comment by ptaoussanis** [comment]
Hi there,

Didn't look at this in detail, but one of the first things I'd suggest is ruling out that you're running into issues with ApacheBench (which tends not to scale very well with concurrency). 

You might find https://github.com/ptaoussanis/clojure-web-server-benchmarks useful re: other tooling + config ideas, etc.

Cheers :-)

**Comment by dfdx** [comment]
That makes sense. Could please also suggest parameters to wrk2 that are equivalent to what I used for `ab`? Namely, I need to test from 100 to 10000 concurrent non-keepalive requests. So far I used this:

    ./wrk --header "Connection: Close" -t 16 -c 16 -R 10000 http://127.0.0.1:8080/

This produces latencies of about 70ms which looks is similar to what I've got with ApacheBench, but I'm totally not sure about `-c` parameter.

**Comment by dfdx** [comment]
Seems like I misinterpreted results - with detailed latency log (`-L` flag) I see that ~90% of non-keepalive requests just fail. I found a related bug in in wrk2 - giltene/wrk2#5 - but from the code it looks like it has been already fixed. Have anyone encountered similar issues with wrk2 and non-keepalive connections?

**Comment by milindbenjamin** [comment]
whats ./wrk ?

**Comment by dfdx** [comment]
`./wrk` refers to a call to [wrk2](https://github.com/giltene/wrk2) benchmarking tool.

**Comment by ptaoussanis** [comment]
Going to close as part of issue triage since this we're getting outside the scope of http-kit. Best of luck!
