### ISSUE TITLE
Getting opcode mismatch warnings

### ISSUE THREAD

**Issue by jwr** [http-kit/http-kit#296]
I'm getting `opcode mismatch` warnings in my logs in a long-running application (using long-lived sente websockets, in case it matters). They are not very frequent, and often appear in groups, like the one below:

```
Tue Jun 14 08:19:15 CEST 2016 [server-loop] WARN - opcode mismatch: pre: 1, now: 0
Tue Jun 14 08:19:46 CEST 2016 [server-loop] WARN - opcode mismatch: pre: 1, now: 0
Tue Jun 14 08:21:14 CEST 2016 [server-loop] WARN - opcode mismatch: pre: 1, now: 0
Tue Jun 14 08:21:32 CEST 2016 [server-loop] WARN - opcode mismatch: pre: 1, now: 0
Tue Jun 14 08:21:56 CEST 2016 [server-loop] WARN - opcode mismatch: pre: 1, now: 0
Tue Jun 14 08:22:22 CEST 2016 [server-loop] WARN - opcode mismatch: pre: 1, now: 0
Tue Jun 14 08:22:48 CEST 2016 [server-loop] WARN - opcode mismatch: pre: 1, now: 0
Tue Jun 14 08:23:07 CEST 2016 [server-loop] WARN - opcode mismatch: pre: 1, now: 0
Tue Jun 14 08:23:26 CEST 2016 [server-loop] WARN - opcode mismatch: pre: 1, now: 0
```

I am not sure what to make of it. I traced them down to http-kit, but I am way too far from understanding the code to make any progress.

**Comment by venantius** [comment]
Hey @jwr -- what version of http-kit are you using? Something like this has surfaced previously but it should be fixed in more recent versions, and certainly on master.

**Comment by jwr** [comment]
I have `2.1.19` in production, which is where I see these messages. I am testing `2.2.0-alpha2` in my development environment, and I'm not seeing anything here, but then these messages happened only in production, and only after a certain time.

Has this been fixed past `2.1.19`?

**Comment by ptaoussanis** [comment]
> I have 2.1.19 in production, which is where I see these messages. 

Please note that 2.1.19 is now quite old, and contains known bugs. Changelog is available at https://github.com/http-kit/http-kit/releases

> Has this been fixed past 2.1.19?

I believe so, yes (see issue #248).

**Comment by jwr** [comment]
Thank you. In that case, I'm sorry for the noise. I would suggest closing this bug then, I will keep it bookmarked and report back once I install 2.2.0 in production. This probably will not happen sooner than in several weeks, however.

**Comment by ptaoussanis** [comment]
No problem. Regret the current confusion re: the "stable" vs alpha release; unfortunately couldn't be avoided.

The current dev branch is on track to hitting beta soon + will hopefully go stable soon after that.
