### ISSUE TITLE
HTTP2 Support

### ISSUE THREAD

**Issue by sambathl** [http-kit/http-kit#299]
What's the plan to support http2? :)

**Comment by ptaoussanis** [comment]
Hi there, no plans. The recommendation is to run http-kit behind something like nginx, which can provide HTTP/2 support. Cheers! :-)

**Comment by tipok** [comment]
Hi, but you do not get any benefits running behind a HTTP/2 proxy, other than clients not supporting HTTP/1.1 could use your service.
Because you will talk HTTP/1.1 in your application you will not be able to push stuff from server or having just one connection and a lot of file requests etc.

**Comment by x3ro** [comment]
That's unfortunate @ptaoussanis. I was planning to use httpkit for a [webpush push service](https://datatracker.ietf.org/doc/draft-ietf-webpush-protocol/) implementation, but that'd require HTTP/2 support. Are you aware of any other efforts in the Clojure community to implement an HTTP/2 server lib?

**Comment by ptaoussanis** [comment]
No idea, sorry - you'd need to Google it.

Please also note that trying to implement an entire HTTP/2 server lib for Clojure would be a significant undertaking full of potential issues, including (still) a lack of widespread client support. You'd also likely see worse performance than by just going through nginx.

Even nginx's HTTP/2 support is still fairly recent + immature.

**Comment by tipok** [comment]
@x3ro this adapter ring jetty adapter should support WebSockets and HTTP/2 [ring-jetty9-adapter](https://github.com/sunng87/ring-jetty9-adapter)

**Comment by agarman** [comment]
@x3ro [immutant](http://immutant.org/documentation/current/apidoc/guide-web.html) also supports WebSockets & HTTP/2
