### ISSUE TITLE
Support for arrays in form params

### ISSUE THREAD

**Issue by erez-rabih** [http-kit/http-kit#301]
Hi,

I am trying to use http kit to communicate with Stripe API

I have a problem communicating array types to the API, for example to create a Product you have to pass an array of attributes the following way:

```bash
$ curl https://api.stripe.com/v1/products \
   -u your-key-here: \
   -d name=T-shirt \
   -d description="Comfortable gray cotton t-shirts" \
   -d attributes[]=size \
   -d attributes[]=gender
```
As you see, Stripe expectes two attributes[]=attr in its form params.
I tried passing the following as :form-params option to the create product request:
```clojure
{:name "T-shirt" :description "desc" :attributes ["size" "gender"]}
```
But Stripe does not accept the request stating the attributes array is invalid.
I had a look at the query-string implementation here: https://github.com/http-kit/http-kit/blob/master/src/org/httpkit/client.clj#L47
And it looks like the array is translated into:
```
attributes=size&attributes=gender
```
so Stripe does not accept it as a valid array
Is there any way to affect the way http-kit translates array into form params or do I have to create my own encoder and put the result directly into the :body attribute of the request?

When considering this problem we should also take in mind arrays of nested objects like the following:
```bash
$curl https://api.stripe.com/v1/orders \
   -u your-key-here: \
   -d items[][type]=sku \
   -d items[][parent]=Product1 \
   -d items[][type]=sku \
   -d items[][parent]=Product2 \
   -d currency=usd \
   -d email="jenny@ros.en"
```

**Comment by erez-rabih** [comment]
Just wanted to update that I ended up writing my own library to convert my params map into a valid HTTP encoded form params and inserting it directly into the request option :body.

You can find the library here: https://github.com/nanit/paraman

**Comment by ptaoussanis** [comment]
Great, thanks for the update! Cheers :-)
