### ISSUE TITLE
Seems that http-kit accepts self-signed SSL certs by default

### ISSUE THREAD

**Issue by hiredgunhouse** [http-kit/http-kit#316]
I have a site with self-signed cert and http-kit does not complain about it.
This is probably not a good default  behavior for HTTPS connections.

**Comment by ptaoussanis** [comment]
Thanks for the report. Would be happy to take a look at a PR to adjust default behaviour, cheers! :-)

**Comment by hiredgunhouse** [comment]
I can give it a try but I can't promise anything,

**Comment by javahippie** [comment]
I tried to reproduce the behavior with http-kit 2.2.0, unfortunately I was not able to do so. I tried the following call:

`@(client/get "https://self-signed.badssl.com/")`

Result:

    http-kit-ssl-test.core> @(client/get "https://self-signed.badssl.com/")
    {:opts {:method :get, :url "https://self-signed.badssl.com/"}, :error #error {
     :cause "unable to find valid certification path to requested target"
     :via
     [{:type javax.net.ssl.SSLHandshakeException
       :message "General SSLEngine problem"
       :at [sun.security.ssl.Handshaker checkThrown "Handshaker.java" 1431]}
      {:type javax.net.ssl.SSLHandshakeException
       :message "General SSLEngine problem"
       :at [sun.security.ssl.Alerts getSSLException "Alerts.java" 192]}
      {:type sun.security.validator.ValidatorException
       :message "PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"
       :at [sun.security.validator.PKIXValidator doBuild "PKIXValidator.java" 387]}
      {:type sun.security.provider.certpath.SunCertPathBuilderException
       :message "unable to find valid certification path to requested target"
       :at [sun.security.provider.certpath.SunCertPathBuilder build "SunCertPathBuilder.java" 141]}]
     :trace

**Comment by ptaoussanis** [comment]
@javahippie Beautiful Tim, thank you - that's a huge help! Closing.
