### ISSUE TITLE
Websockets with Internet Explorer cause intense load

### ISSUE THREAD

**Issue by mikkosuonio** [http-kit/http-kit#322]
I am using http-kit and Sente to communicate with clients (Chrome and Internet Explorer) via websockets. My application exhibits a high CPU load on the server with little user activity.

The reason for this turned out to be idle IE browsers sending unsolicited pong frames to the server. The server needs to respond to this pong frame as otherwise IE will send an invalid message and cause the connection to terminate.

http-kit contains a fix for this in https://github.com/http-kit/http-kit/pull/134. This fix instructs http-kit to respond with a ping frame.

However, that response causes the client to send another pong frame, as required by the websocket spec. This is understood as another unsolicited pong frame by the server. This will be a start of an intense match between the server and the client.

I prepared a proto which responds with a pong frame. This seems to satisfy the client and produces only occasional messaging.

https://github.com/mikkosuonio/http-kit/tree/mikkosuonio-http-kit-ie-ping-pong

Would this response be appropriate for an unsolicited pong frame sent by IE?

**Comment by mikkosuonio** [comment]
Some http libraries/frameworks have solved this by ignoring unsolicited pong frames. This requires that a higher-level component (like Sente) implements keepalive messaging to prevent IE from disconnecting.

**Comment by ptaoussanis** [comment]
Hi Mikko, thanks for identifying this issue- PR welcome!

Sorry for the delay responding.

**Comment by ptaoussanis** [comment]
Ref. https://github.com/ptaoussanis/sente/issues/287

**Comment by ptaoussanis** [comment]
Hi Mikko, thanks for identifying the issue here (and apologies for the slow response)!

Upstream PR for http-kit would be welcome!

**Comment by mikkosuonio** [comment]
Here is a candidate fix. I adjusted the tests for no response to pong frames. After this the tests pass on most runs. However, I get exceptions according to test logs in org.httpkit.server-test and org.httpkit.client-test, but no test failures.

I did not adjust the version in project.clj.

**Comment by ptaoussanis** [comment]
Merging now!

**Comment by mikkosuonio** [comment]
Excellent, glad to be able to contribute!

**Comment by peterlondon** [comment]
It is not my experience (March 2019) that IE pongs can be ignored.
It does seem to time out after quite a short while if it gets no response as was initially thought above
But I have found that a pong in response to IE's pongs (pong/pong instead of ping/pong)
seems to keep the browser happy and the connection alive

Secondly a small aside I had wrongly assumed that a zero data length would mean no mask.
But I was wrong. IE sends the 4 bytes of mask with the pong, even though there is no data

**Comment by peterlondon** [comment]
I thought I had seen IE/Edge timing out if their pongs were not responded to,
in the way that was originally thought above.
But that may have been when I was not taking into account the fact the IE/Edge sends the mask even though there is no data in the pong frame
