### ISSUE TITLE
Metrics event instrumentation

### ISSUE THREAD

**Issue by kumarshantanu** [http-kit/http-kit#323]
Http-Kit knows about several events that would be useful to emit and aggregate outside of the server. Examples include: latency of the hostname resolution in http-client, the times when the server responded with HTTP 503 because the request queue was full etc.

I have been maintaining a fork for quite some time that allows one to _optionally_ pass event logger as argument to capture various events. The overhead when one doesn't want any logging is practically zero due to JVM JIT's empty-method-body elimination. This fork has seen over 6 months of production use so far. It has helped troubleshoot infrastructure bug and server behavior under load via metrics logging/aggregation. (I would be happy to offer the changes I have maintained as a pull request, and to make any further changes needed to make the PR suitable for merging.) The URL of the fork diff is below:
https://github.com/http-kit/http-kit/compare/master...kumarshantanu:logging?expand=1

**Comment by ptaoussanis** [comment]
Hi @kumarshantanu, sorry for the crazy delay responding!

Would definitely be open to seeing a PR for this, thank you!

**Comment by ptaoussanis** [comment]
Somehow missed closing this earlier, Shantanu's PR was merged in 2017 👍
