### ISSUE TITLE
Caused by: java.lang.NoSuchMethodError: org.httpkit.client.RequestConfig.<init>(Lorg/httpkit/HttpMethod;Ljava/util/Map;Ljava/lang/Object;II)V, 

### ISSUE THREAD

**Issue by xingzhefeng** [http-kit/http-kit#328]
从2.1.19升级到2.2.0的时候出现这个错误.

**Comment by xingzhefeng** [comment]
晕.原来是 线上 repo仓库中的2.2.0 是错误的.
我git clone 编译后 把 clojure的 版本从1.6 改为 1.8 
  ;:javac-options ["-source" "1.6" "-target" "1.6" "-g"] 删除这个. 
发布到私有仓库2.2.1 [http-kit "2.2.1"] 就没有问题了.

**Comment by ptaoussanis** [comment]
Hi @xingzhefeng, have you tried `lein clean`? Is this still a problem?

**Comment by mdiin** [comment]
@ptaoussanis I am seeing this particular exception in a small project built with boot. With boots concept of filesets, there is no clean task, and the output directory cannot contain stale data, so I am unsure how to start debugging this. The project in question is https://github.com/mdiin/hexperiment - it is fairly minimal. Running `boot build` produces an uberjar which when run with `java -jar <file>` fails with the above exception.

Looking at the http-kit code embedded within the jar reveals only that the embedded http-kit code should in fact not show this behaviour. The `org/httpkit/server.clj` call to `HttpServer` constructor passes the correct number of arguments according to the constructor in `org/httpkit/server/HttpServer.java`, which is 7 arguments, not the 6 shown in the error: `org.httpkit.server.HttpServer.<init>(Ljava/lang/String;ILorg/httpkit/server/IHandler;III)V`

There is really nothing indicating why this is an issue. My guess is it is not an issue with http-kit, but I don't know where else to start. Any help with this would be much appreciated.

**Comment by mdiin** [comment]
I forgot to mention that the issue is not present when the code is run from the boot repl; only the jar has a problem.

**Comment by mdiin** [comment]
I found the problem: In my case it was a dependency conflict between weasel and replikativ, which weasel won; thus causing an old version of httpkit to be used for the final jar.
