### ISSUE TITLE
Issue with using http-kit client with domain name containing underscore character

### ISSUE THREAD

**Issue by williamlee** [http-kit/http-kit#336]
Hi,

We've encountered an issue when using http-kit client to connect to a internal service (in a Docker cluster) that has host name containing underscore character. As I understand it the RFC for URI doesn't support underscore in the hostname portion of an URI, however the Docker service link generates domain name for service with underscore in the name. 

I have traced through the code and see that the cause of the issue ("host is null") is because in HttpClient.java (line 236), it uses the java.net.URI() class to parse the URL and java.net.URI() will silently return null with the getHost() call. So a change to use the java.net.URL() class instead of the URI() class to parse the components will work. 

I'm not sure if I'm the only one who has this weird and unfortunate issue. It will be nice if there is a workaround for this. In the meantime I'll have to use something else other than http-kit.

William

**Comment by sundbry** [comment]
You should probably address the issue upstream in your stack, whether it is a bug in Docker producing an illegal name, or your service needs to be renamed. This would not be a bug in http-kit.

**Comment by ptaoussanis** [comment]
Agree with Ryan on this, closing. (Thanks @sundbry!)
