### ISSUE TITLE
Convey dynamic bindings to client callback fn?

### ISSUE THREAD

**Issue by aiba** [http-kit/http-kit#339]
In `core.async` code it's nice to be able to combine dynamic variables with async code, such as:

```clj
(binding [*foo* true]
  (go ... (println *foo*)) ;; different thread but *foo* still true
```

In httpkit, dynamic bindings are lost in the callback:

```clj
(binding [*foo* true]
  (org.httpkit.client/get "http://www.example.com/" {}
                          (fn [r]
                            ;; binding lost, *foo* no longer true
                            (println *foo*))))
```

I'm working around this by calling the `clojure.core/binding-conveyor-fn`, but this seems sketchy because this is a private function and I don't fully understand the implications.  (Is there a performance hit?  Am I unleashing other gremlins into my runtime?)

```clj
(binding [*foo* true]
  (org.httpkit.client/get "http://www.example.com/" {}
                          (#'clojure.core/binding-conveyor-fn
                           (fn [r]
                             ;; *foo* still true
                             (println *foo*)))))
```

Should http-kit convey dynamic bindings to the callback by default?

**Comment by aiba** [comment]
To follow up on this, I've adopted this wrapper on client requests to make httpkit work well core.async:

```clj
(defn client-request [req]
  (let [ret (async/promise-chan)]
    (org.httpkit.client/request req #(async/put! ret %))
    ret))
```

This preserves dynamic bindings (since go blocks preserve dynamic bindings) and easily switch from async to sync (by wrapping in `<!!`).

Since `core.async` is popular, maybe it'd be worth adding a page of documentation on http://www.http-kit.org/ with some suggestions for using http-kit async with `core.async`.  If the project maintainers are interested in this, I'd be happy to write a draft with examples.

**Comment by ryfow** [comment]
Shouldn't you be able to use use `bound-fn`?

**Comment by aiba** [comment]
Oh yeah, didn't know about `bound-fn`, that would do the trick.

I still think it would be worth documenting what the story is for http-kit and core.async.
