### ISSUE TITLE
Have control over when pings are sent and received over ws

### ISSUE THREAD

**Issue by vincentjames501** [http-kit/http-kit#350]
In node.js or the browser (and many other websocket clients/servers), you can listen for PING/PONG events as well as issue PINGs at any time manually. This functionality would be nice to have in both the client and server as we need these heartbeats in our system..

**Comment by ptaoussanis** [comment]
Closing as part of issue triage since this was at least partially addressed by #352 and there's been no further activity in the meantime.

Feel free to re-open if this is still relevant.
