### ISSUE TITLE
Java 9 deps problem `javax.xml.bind.DatatypeConverter` missing

### ISSUE THREAD

**Issue by claj** [http-kit/http-kit#356]
# Problem

When upgrading my JVM to 9.0.1 there is a problem with a javax.xml.bind.DatatypeConverter class missing. This makes http-kit client unusable on JVM 9 which I consider serious.''

# http-kit version
`[http-kit "2.2.0"]`, `[http-kit "2.3.0-alpha4"]`

# Java version
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

# Stack trace
`Caused by: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter, compiling:(org/httpkit/client.clj:1:1)
	at clojure.lang.Compiler.load(Compiler.java:7526)
	at clojure.lang.RT.loadResourceScript(RT.java:379)
	at clojure.lang.RT.loadResourceScript(RT.java:370)
	at clojure.lang.RT.load(RT.java:460)
	at clojure.lang.RT.load(RT.java:426)
	at clojure.core$load$fn__6550.invoke(core.clj:6051)
	at clojure.core$load.invokeStatic(core.clj:6050)
	at clojure.core$load.doInvoke(core.clj:6034)`

# suggested solution

Something like[ inlining a base64 encoder into the source code](https://github.com/jexler/grengine/commit/659f4fe8a5433339bb6ac591d79a687374687dc7).

One example of the source of the [javax.xml.bind.DatatypeConverter](http://grepcode.com/file/repository.jboss.org/nexus/content/repositories/releases/org.jboss.embedded/thirdparty-all/beta3.SP15/com/sun/xml/bind/DatatypeConverterImpl.java#DatatypeConverterImpl._printBase64Binary%28byte%5B%5D%29) is however a little more elaborate, and makes closer considerations than the code in grengine above on the allocated string buffer size etc.

**Comment by zentrope** [comment]
You can get around this with:

    --add-modules java.xml.bind

or in Lein:

    :jvm-opts ["--add-modules" "java.xml.bind”]

but then you need a conditional build somehow if you intend your project to be backwards compatible given that Java 8 will fail with that particular switch.

**Comment by claj** [comment]
Thanks a lot for that switch. It will work in our particular case.

Are you interested in a patch which either

a) inlines the functionality

b) adapts based on JVM-version or class availiability (by some Class/forName logic running once or similar)

c) simply point to work-arounds

d) do something else about this problem altogether?

**Comment by randomizedthinking** [comment]
@zentrope The `:jvm-opts` does not work in my case. Basically, I tried to used `gorilla-repl`, and it refers`http-kit` as one of its internal dependencies. Yet, `gorilla-repl` is a plugin to the project. Somehow the `jvm-opts` you suggested does not work under such scenarios.

Just wonder is there any way to have the lein plugin initialization also receive the `jvm-opts`?

**Comment by zentrope** [comment]
@randomizedthinking Of course the real fix is to remove the javax.bind dependency in the first place for this project.

There are other ways to add options:

* Check the bottom of [sample-project](https://github.com/technomancy/leiningen/blob/stable/sample.project.clj) for additional lein options.

* Maybe [env vars](https://bugs.openjdk.java.net/browse/JDK-4971166) (JAVA_TOOL_OPTIONS) for Java itself might work if you set it in your shell.

**Comment by randomizedthinking** [comment]
@zentrope Thanks! I tried both approaches, but none  works.

* `gorilla-repl` uses `eval-in-project`, and I didn't find an option to pass extra options to it in the lein sample-project;
* `JAVA_TOOL_OPTIONS` was picked by JVM, good, yet other  strange errors occur with it. Maybe I need to pass complete parameters when using this option.

**Comment by randomizedthinking** [comment]
@zentrope After another round of trials, it is confirmed that `JAVA_TOOL_OPTIONS` can be used  to pass jvm initialization parameters to the plugins. Thanks a lot for the information.

**Comment by lungsi** [comment]
@zentrope Can you please provide the details how you got `lein gorilla` to work?
I am trying to use `gorilla-repl` (for the first time) but I am also getting a similar error presumably due to java9
`clojure.lang.Compiler$CompilerException: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter, compiling:(org/httpkit/server.clj:1:1)
 at clojure.lang.Compiler.load (Compiler.java:7391)
...`

**Comment by ptaoussanis** [comment]
Hi @claj, would be up for seeing an inlining PR- thanks! :+1:

**Comment by benalbrecht** [comment]
Since java 8, there is a `java.util.Base64` class available for base64 encoding.
i hacked up a quick macro to use whichever of the two is available.

should i prepare a PR with this solution?

```clojure
(defmacro base64-encode [bs]
  (if (try (import 'javax.xml.bind.DatatypeConverter)
           (catch ClassNotFoundException _))
    `(javax.xml.bind.DatatypeConverter/printBase64Binary ~bs)
    (do
      (import 'java.util.Base64)
      `(.encodeToString (java.util.Base64/getEncoder) ~bs))))
```

**Comment by claj** [comment]
(Added a PR with @benalbrecht 's clever macro loading code.)

**Comment by ptaoussanis** [comment]
@claj Great, thanks Linus- checking now :+1:

**Comment by ptaoussanis** [comment]
Just cut [2.3.0-beta2](https://github.com/http-kit/http-kit/releases/tag/2.3.0-beta2) which includes this fix, thanks all! :+1:

**Comment by yottabytt** [comment]
> @zentrope Can you please provide the details how you got `lein gorilla` to work?
> I am trying to use `gorilla-repl` (for the first time) but I am also getting a similar error presumably due to java9
> `clojure.lang.Compiler$CompilerException: java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter, compiling:(org/httpkit/server.clj:1:1) at clojure.lang.Compiler.load (Compiler.java:7391) ...`

export JAVA_TOOL_OPTIONS="--add-modules=java.xml.bind"
