### ISSUE TITLE
[bug] Response of one request gets delivered to another request

### ISSUE THREAD

**Issue by rkaippully** [http-kit/http-kit#361]
version: `2.3.0-alpha4`

I encountered this interesting bug in http-kit client. The symptom was that a few times a day some of our POST requests to a server running Tomcat will return a response that is intended for another request executed concurrently sharing the same http client. For e.g. if requests R1 and R2 are running concurrently in two threads and share the same `HTTPClient`, R2 gets the response of R1 and R1 eventually times out. When we inspected the logs from the server, it showed that the server sent both the responses correctly.

After quite some debugging it turned out that there is a subtle bug in the parsing logic for chunked responses that can cause this. I have a fix for this undergoing testing. If you are interested I can send a pull request from my fork (https://github.com/rkaippully/http-kit) as soon as I complete testing.

This sounds similar to the issue reported in #338, but I am not sure if it is the same bug. That issue seem to be affecting the server, this issue is for the client.

**Comment by rkaippully** [comment]
Here is a detailed explanation of the bug:

HTTP chunked transfer encoding requires the response to end in CRLF characters. However, it is possible that the CR and LF characters are split into two TCP packets and will not be read into the same byte buffer. CR will be the last byte of one read and LF will be the only content of the next read. The logic in `Decoder.readEmptyLine()` assumes that decoder reached `ALL_READ` state if CR is the last character in the buffer. Later when LF arrives in the next packet it will be ignored.

This implies that when `HTTPClient.doRead()` invokes `Decoder.decode()`, it will detect that the decoder reached ALL_READ state twice. First on reading the CR character and then on the LF character. Whenever the state is equal to `ALL_READ` it creates a `PersistentConn` object for the `SelectionKey` and adds it to the `keepalives` queue. So we end up with two keep-alive connections both using the same channel.

This is a recipe for disaster. If two subsequent concurrent requests manage to attach to these two keep-alive connections, they will send their requests on the same channel. But both responses will be processed by the handler of the last request that attached to the `SelectionKey`. Thus one of those two requests will get the response of the other request.

**Comment by jiacai2050** [comment]
@rkaippully Good job! 
How was the PR going? Is there anything I can help?

**Comment by rkaippully** [comment]
I have raised PR #362 already, would appreciate if someone can review and merge it.

**Comment by aiba** [comment]
I'm pretty sure I'm experiencing this bug as well.  My company does about 400,000 requests/day on a single JVM using http-kit, and we see a criss-crossed response about once per week.

When it happens, it really screws things up and we have to halt our system to manually repair it.  Until today, I thought it must be a race condition in our own code, but after careful review I narrowed it down to http-kit and then saw this issue, which would perfectly explain all the examples we've seen.

I'd just like to chime in and note that I would be oh so grateful if this PR could be reviewed and merged in!

**Comment by ptaoussanis** [comment]
Excellent Raghu- thank you for the investigation, clear report, and PR- merging manually now!

**Comment by ptaoussanis** [comment]
`[http-kit "2.3.0-alpha5"]` is now on Clojars, thanks everyone :+1:
