### ISSUE TITLE
Failed TLS handshake with the client results in a ProtocolError "No Response"

### ISSUE THREAD

**Issue by teeohhem** [http-kit/http-kit#364]
Failed TLS handshake using the http-kit client results in a ProtocolError "No Response" exception. There is no other information about why the client connection fails. Using the latest stable build.

**Comment by jiacai2050** [comment]
Try `2.3.0-alpha4`, sni support has been added to solve this issue.

**Comment by teeohhem** [comment]
Awesome! Thank you!
