### ISSUE TITLE
Expose client/query-string

### ISSUE THREAD

**Issue by jorinvo** [http-kit/http-kit#385]
http-kit is a great simple library. Thanks for all your work!

Was wondering if it is possible to make the private function `query-string` public?
Feel like I'm not the only one copy that function (or writing a similar one).

If you are interested in that change, I'm happy to submit a PR, thanks :)

**Comment by kirked** [comment]
Heh, #389 opened last night. I want it too, but "borrowed" it in the meantime!

**Comment by ptaoussanis** [comment]
PR merged 👍

**Comment by kirked** [comment]
Thanks Peter!
