### ISSUE TITLE
Chunk encoded request

### ISSUE THREAD

**Issue by niquola** [http-kit/http-kit#386]
I want to send large files to http-kit server using "Chunked transfer encoding"  and process it in stream without eating all memory.
Is it possible with http-kit and (if not) how complicated to implement this?

**Comment by niquola** [comment]
Can the client read a chunked response chunk by chunk?

**Comment by hkorpi** [comment]
Chunked encoding works using async channels e.g. 
`(http-kit/as-channel
    request
    {:on-open
     (fn [channel] (send! channel ...))})`

**Comment by ptaoussanis** [comment]
Closing as part of issue triage, feel free to re-open if this question is still relevant.
