### ISSUE TITLE
retry - how does it work? No info in doc.

### ISSUE THREAD

**Issue by kwladyka** [http-kit/http-kit#390]
How does it work in `[org.httpkit.client :as http]` ?
Can I control it?

I suffer issues for months about double requests to server with difference 1 second to make invoice. I can't find the source of the problem. Maybe `@(http/post url request)` repeat query in some specific situation?

Can I set it to not retry to be 100% sure?

Edit:
I found the source of the issue. But still I am curious how retry works with http-kit.

**Comment by ptaoussanis** [comment]
> I found the source of the issue.

@kwladyka For the benefit of others, could you please provide some more info? Thanks!

**Comment by kwladyka** [comment]
It was 2 years ago. The issue was my mistake in code which send request more than once. I didn't find how retry work in http-kit.

**Comment by ptaoussanis** [comment]
> The issue was my mistake in code which send request more than once. 

👍 Thanks for clarifying, that's useful to have documented for others.

> I didn't find how retry work in http-kit.

Iirc http-kit client doesn't do any automatic retrying, you'd need to handle retries from your side.
