### ISSUE TITLE
How can we contribute to documentation / site examples?

### ISSUE THREAD

**Issue by huima** [http-kit/http-kit#392]
We're using http-kit a lot at work and would like to contribute also to docs to make http-kit more usable. At the moment you need to find stuff via google and hope the info is still valid. Good example being SNI support.

I just started to update some apps to JDK 11 and tested 2.4-alpha3. I noticed that the olf configurator code was not sufficient, but needed also client mode to be set to true explicitly.

```clojure
(defn sni-enabled-ssl-configurer
  [^SSLEngine ssl-engine ^URI uri]
  (let [^SSLParameters ssl-params (.getSSLParameters ssl-engine)]
    (.setServerNames ssl-params [(SNIHostName. (.getHost uri))])
    (.setSSLParameters ssl-engine ssl-params)
    (.setUseClientMode ssl-engine true)))
```

**Comment by kumarshantanu** [comment]
FWIW I have updated the blog post on HTTP-Kit/SNI on setting client mode: https://medium.com/@kumarshantanu/using-server-name-indication-sni-with-http-kit-client-f7d92954e165

Thanks, @huima!

**Comment by ptaoussanis** [comment]
Hi Heimo, sure- thanks for asking!

I'd suggest the GitHub Wiki, since then you don't need to block on me or other reviewers to make changes.

All the best!
