### ISSUE TITLE
When reusing connection, isConnected and timeoutTs are not set properly

### ISSUE THREAD

**Issue by ethpran** [http-kit/http-kit#401]
I might be wrong about this, so I'm double checking before submitting a fix. When [successfully reusing a connection from the keepalives cache](https://github.com/http-kit/http-kit/blob/master/src/java/org/httpkit/client/HttpClient.java#L423), it doesn't look like the request updates its `isConnected` and `timeoutTs` fields like it does after connecting for the first time in the [setConnected](https://github.com/http-kit/http-kit/blob/master/src/java/org/httpkit/client/Request.java#L41) method. This seems like a bug which could cause unwanted consequences in [clearTimeout](https://github.com/http-kit/http-kit/blob/master/src/java/org/httpkit/client/HttpClient.java#L123) in which we use the wrong timeout as defined in request params and the wrong error message.

**Comment by xwang1498** [comment]
I've proposed PR #481 to fix this.

**Comment by ptaoussanis** [comment]
Manually merging xwang1498's PR now! Thanks for the report @ethpran.
