### ISSUE TITLE
Non-snapshot Java 11 release?

### ISSUE THREAD

**Issue by benfb** [http-kit/http-kit#404]
Hey,

Is there any chance you could cut a non-snapshot release that supports Java 11? I could use the snapshot, but I don't want to ship a tool that other users rely on that pulls in a snapshot that could change as a dependency.

Thanks!

**Comment by bowbahdoe** [comment]
Same here, but for Java 12

**Comment by ptaoussanis** [comment]
Hi there! `[http-kit "2.4.0-alpha3"]` includes Java11+ support 👍

**Comment by perkola** [comment]
Apologies for commenting on a closed issue @ptaoussanis, but I thought this issue was similar to my question: I have been running `2.4.0-alpha6` for a few weeks on Java11 and it seems stable. What are the criteria to create and publish a non-alpha release such as `2.5.0`?

**Comment by ptaoussanis** [comment]
@perkola Hi William, a few things:

- Passage of wall clock to let last changes settle and receive feedback + issue reports.
- Free time on my end (or from contributors) to investigate feedback + issue reports.
- Free time on my end to document + cut a new release.

I'll note that we're some ways off from a stable `2.4.0` - would first go to beta, then RC.
