### ISSUE TITLE
dependency complication

### ISSUE THREAD

**Issue by laforge49** [http-kit/http-kit#406]
Been working on the backend too long. Now trying to update my sente-boot example and running headlong into a dependency issue (methinks) with http-kit. My build-boot file is located here: https://github.com/laforge49/sente-boot/blob/master/build.boot 

Below is the error. Any help would be appreciated. Bill

      clojure.lang.ExceptionInfo: clojure/lang/IFn
    data: {:file "org\\httpkit\\server.clj", :line 66}
  java.lang.NoClassDefFoundError: clojure/lang/IFn
java.lang.ClassNotFoundException: clojure.lang.IFn
                                   ...
                  clojure.core/load/fn                          core.clj: 6007
        clojure.core/load/invokeStatic                          core.clj: 6006
                     clojure.core/load                          core.clj: 5990
                                   ...

**Comment by ptaoussanis** [comment]
Hi Bill, have you tried checking for possible dependency conflicts and cleaning out build artefacts?

**Comment by ptaoussanis** [comment]
Closing as part of issue triage due to inactivity.
Please feel free to re-open if this issue is still relevant.
