### ISSUE TITLE
https server support

### ISSUE THREAD

**Issue by jarod95** [http-kit/http-kit#409]
Https server is not supported, it is usefull, please consider adding it. Thanks.

Best Regards
Jarod Yao

**Comment by ptaoussanis** [comment]
Hi there,

There are no plans for http-kit server to support HTTPS - the recommendation is to run your web server behind a mature reverse-proxy (nginx, etc.).

See also https://github.com/http-kit/http-kit/issues/146, and (I think) a few others issues where this has been discussed.

Thanks!
