### ISSUE TITLE
Disable sending the "Server" header

### ISSUE THREAD

**Issue by barkanido** [http-kit/http-kit#432]
Currently, the _server_ header is sent hard coded in `DataFormatter.HttpEncode`:
```java
        if (!headers.containsKey("Server")) {
          headers.put("Server", "http-kit");
        }
```
this is considered a security problem and is [discouraged by the RFC](https://www.w3.org/Protocols/rfc2616/rfc2616-sec15.html):

> Implementors SHOULD make the Server header field a configurable option.

For us, this means also a reduction in our outgoing data AWS bills ;-).

The only configuration hook available currently is the map given to `run-server`.
Would you be interested in a PR allowing this kind of configuration?

**Comment by ptaoussanis** [comment]
Hi there! PR welcome at https://github.com/http-kit/http-kit/issues/129.
Closing here as a duplicate.

> The only configuration hook available currently is the map given to run-server.
Would you be interested in a PR allowing this kind of configuration?

Yes, that's perfect. Please allow configuration of an arbitrary Server header string, which can be nil (=> disabled).

Cheers!

**Comment by barkanido** [comment]
will do.
