### ISSUE TITLE
Syntax error (ClassNotFoundException) compiling at (app/api.clj:1:1). org.httpkit.client.SslContextFactory

### ISSUE THREAD

**Issue by ouvanous** [http-kit/http-kit#436]
Hi, 

When upgrading to 2.4.0 version i have this error. 
I can't see what i am doing wrong? 

Many thanks for any tip
Samuel

**Comment by ptaoussanis** [comment]
Hi Samuel, could you please try `lein clean` and see if that helps? (I suspect you may have bad artifacts on your class path).

**Comment by ouvanous** [comment]
Hi Peter, 
That was that ... Sorry 
and many thanks for your help. 
Samuel

**Comment by pesterhazy** [comment]
Ran into the same problem, `lein clean` helped
