### ISSUE TITLE
called server-stop! without option parameter returns error when used "withlegacy-return-value? false"

### ISSUE THREAD

**Issue by franzherzog** [http-kit/http-kit#441]
Problem that occured after calling server-stop! without options:

``` 
(reset! api-server (server/run-server handler {:port 8082 :legacy-return-value? false}))
(server/server-stop! @api-server)
```
returns error:

   No single method: server_stop_BANG_ of interface:
   org.httpkit.server.IHttpServer found for function: server-stop! of protocol:
   IHttpServer

It would be nice for beginners if empty "opts" parameter should be handled also with a default of {} or a better error description would be returned

**Comment by franzherzog** [comment]
For those who are looking for an fix:

```  (server/server-stop! @api-server {}) ```

or use with timout

``` (server/server-stop! @api-server {:timout 500})```

stops the server gracefully

**Comment by ptaoussanis** [comment]
Hi @franzherzog!

A zero-arity version of this fn would be convenient, I'll add one 👍 

However I'd also note a general suggestion (esp. for beginners)- which would be to always try check the docstring or function signature of the API you're using. Most IDEs will show you the necessary arguments as you're typing out the function call, and some will even be able to immediately point out calls with the wrong arity.

This'll be a lot more reliable in the general case.

Cheers!
