### ISSUE TITLE
Move require of org.httpkit.client in sni-client namespace to top-level

### ISSUE THREAD

**Issue by borkdude** [http-kit/http-kit#447]
Code that uses runtime require generally generates +30MB larger binaries than those without. Since `sni-client/default-client` contains a runtime require (inside a delay), compiling that along with babashka generated a ~100mb binary instead of ~68mb.

This is how I could work around it:

Instead of using the `sni/default-client` directly var I created the default client like:

``` clojure
(def sni-client (delay (client/make-client {:ssl-configurer sni-client/ssl-configurer})))
``` 

and voila, I was back to the original binary size.

Maybe this can be documented somewhere OR the code can somehow avoid the runtime require.

I have a library around that here https://github.com/borkdude/dynaload which works well with GraalVM native-image.

**Comment by borkdude** [comment]
Why isn't sni-client loading the `org.httpkit.client` namespace at the top-level - is there a reason to delay this? There's a comment that suggests there would be a circular dependency, but I don't think there is?

**Comment by ptaoussanis** [comment]
@borkdude Hi Michiel! 

> Why isn't sni-client loading the org.httpkit.client namespace at the top-level - is there a reason to delay this?

No reason, this can be changed! This is still an artifact of an earlier version that was toying with making the sni-client available directly in `org.httpkit.client`. Would be happy to cut `v2.5.1` with this change if that'd be helpful?

**Comment by borkdude** [comment]
Not necessary for me since I found a workaround, but for the next version it would be helpful if the runtime require was gone!

**Comment by borkdude** [comment]
@ptaoussanis Changed the title of this issue as a reminder that this should be changed for the next version.
