### ISSUE TITLE
[Doc] Add some directions regarding native-image

### ISSUE THREAD

**Issue by bsless** [http-kit/http-kit#459]
Following #457 building a native image might be less trivial.
I suggest we maintain a short list of the required configuration options to ensure a native image can be built with http-kit and can serve as a reference for other developers

cc: @borkdude

**Comment by borkdude** [comment]
- [ ] strong disagree
- [ ] disagree somewhat
- [ ] agree
- [x] strong agree

**Comment by bsless** [comment]
We should also PR [graalvm-clojure](https://github.com/BrunoBonacci/graalvm-clojure) when 457 is released.
I'll prepare a brief addition to the README

**Comment by bsless** [comment]
Closing after manual merge
