### ISSUE TITLE
GRAAL native-image error with sun.security.provider.NativePRNG for client namespace

### ISSUE THREAD

**Issue by gaberger** [http-kit/http-kit#463]
http-kit compiles and executes as expected when calling out to `run-server`. But when calling out to client code I continue to get 

`
Error: No instances of sun.security.provider.NativePRNG are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=sun.security.provider.NativePRNG.
Detailed message:
Trace: Object was reached by 
        reading field java.security.SecureRandom.secureRandomSpi of
                constant java.security.SecureRandom@32b35ffe reached by 
        reading field sun.security.ssl.SSLContextImpl.secureRandom of
                constant sun.security.ssl.SSLContextImpl$TLSContext@3d38c244 reached by 
        reading field javax.net.ssl.SSLContext.contextSpi of
                constant javax.net.ssl.SSLContext@8899164 reached by 
        scanning method org.httpkit.client.ClientSslEngineFactory.getContextInstance(ClientSslEngineFactory.java:29)
Call path from entry point to org.httpkit.client.ClientSslEngineFactory.getContextInstance(): 
        at org.httpkit.client.ClientSslEngineFactory.getContextInstance(ClientSslEngineFactory.java:29)
        at org.httpkit.client.ClientSslEngineFactory.trustAnybody(ClientSslEngineFactory.java:33)
        at org.httpkit.client$coerce_req.invokeStatic(client.clj:68)
        at org.httpkit.client$coerce_req.invoke(client.clj:60)
        at org.httpkit.server.HttpHandler.run(RingHandler.java:117)
        at java.lang.Thread.run(Thread.java:834)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
        at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
`

This is with the suggested additions to reflect-config and `-H:ClassInitialization=org.httpkit.client.ClientSslEngineFactory:run_time `

**Comment by borkdude** [comment]
Can you try it exactly as written in https://github.com/http-kit/http-kit#native-image?
FWIW, I'm using this in babashka and everything works like expected with these settings. I'm using GraalVM 21.0.0 java11.

**Comment by borkdude** [comment]
I think you are missing the `$SSLHolder` part in your config.

**Comment by gaberger** [comment]
Thanks again @borkdude It turned out my Makefile was munging the inner class.

**Comment by Matsuuu** [comment]
Struggled with this today, and finally found the correct way to set the setting in your makefile.

So if you're using a makefile, make sure to add the flag like so:

```
--initialize-at-run-time=org.httpkit.client.ClientSslEngineFactory\$$SSLHolder 
```

**Comment by bsless** [comment]
Thanks @Matsuuu ,
This is a bit disturbing that this keeps coming up, even though this is due to the mysteries of Make's syntax.
What do you think @borkdude should we add this to the native-image section in the README? Two people independently stumbled across it in less than a week.

**Comment by Matsuuu** [comment]
I think what makes it especially difficult of a situtation is that some people have done their native build configs in their project.clj -files, and some do it in a shell script of a Makefile.

Different languages => Different sytanxes.

A propert example in examples folder or somewhere with both examples would be perfect

**Comment by borkdude** [comment]
@bsless I think it would be good to add a note to the relevant section in the README. 

But I think there is even a better option, which is to include a `native-image.properties` file in `META-INF/native-image/org.httpkit/httpkit` with the following contents:

```
Args = --initialize-at-run-time=org.httpkit.client.ClientSslEngineFactory$SSLHolder
```

With this in place, people should not have to configure something themselves. 

See docs [here](https://www.graalvm.org/reference-manual/native-image/BuildConfiguration/).
