### ISSUE TITLE
Please enable SNI client by default

### ISSUE THREAD

**Issue by kirillsalykin** [http-kit/http-kit#466]
Currently SNI support is disabled by default - this is super confusing (exception is cryptic).

If I understand this is done for compatibility reasons:
```
To retain backwards-compatibility with JVMs < 8, http-kit client's SNI support is DISABLED by default.
```

But I dont think it makes sense to have it disabled by default - cause there are way less users of java 7 and disabled SNI can lead to issues for bigger number of users.

**Comment by borkdude** [comment]
There is already an issue about this: #393

**Comment by kirillsalykin** [comment]
thank you, deleting this one
