### ISSUE TITLE
Possible Out of Memory due to missing back pressure in Server-Sent Events (and elsewhere)?

### ISSUE THREAD

**Issue by holyjak** [http-kit/http-kit#474]
In 2014, Malcom Sparks [described a problem with http-kit and SSE](https://groups.google.com/g/clojure/c/DbBzM3AG9wM/m/hz_o0WUDOM8J) that still seems present:

> http-kit's send! doesn't block normally [..]
> http-kit will attempt to write to the output queue, otherwise will place the message in a pending queue backed by a java.util.LinkedList<ByteBuffer>, so there's no back-pressure (except for that exerted by an OutOfMemory exception)
> AFAICT there's no way of finding whether http-kit's output channel is empty or not, that would certainly be a feature I'd like to see. 

I guess the `if (atta.toWrites.isEmpty()) { ... ch.write(buffers, 0, buffers.length); ... }  else { Collections.addAll(atta.toWrites, buffers); ... }` [in `HttpServer.tryWrite`](https://github.com/http-kit/http-kit/blob/v2.5.3/src/java/org/httpkit/server/HttpServer.java#L315) is what Malcolm meant (where [`toWrites` is `LinkedList<ByteBuffer>`](https://github.com/http-kit/http-kit/blob/v2.5.3/src/java/org/httpkit/server/ServerAtta.java#L7)).

I.e. there is still no back pressure for HTTP Streaming such as SSE and if clients do not read their messages (and there are many), there could be an out-of-memory.

I have not tested it so it is only a hypothesis, but seems likely. Any thoughts about this? 🙏

**Comment by ptaoussanis** [comment]
@holyjak Hi Jakub, thanks for bringing attention to this! Apologies for the delay replying.

I unfortunately won't have an opportunity to look into this myself, but have marked the issue to request input from others.

> there's no way of finding whether http-kit's output channel is empty or not, that would certainly be a feature I'd like to see.

Just to confirm: your concern is that the pending (LinkedList) queue could grow without limits and eventually cause an OOM?

Do we have any idea how likely that is to happen? E.g. how much memory is used for each pending request?

Would access to the pending (LinkedList) queue size not maybe be more useful than knowing whether the output queue is empty? Not familiar with the details here, just going off my understanding of your description.

Thanks!

**Comment by ptaoussanis** [comment]
Possibly related to #407?

**Comment by ptaoussanis** [comment]
Closing as part of issue triage due to inactivity.
If the objective here is wanting info on queue activity, that should be addressed at #407.
