### ISSUE TITLE
GRAAL native-image error with sun.security.provider.NativePRNG 

### ISSUE THREAD

**Issue by askonomm** [http-kit/http-kit#475]
Basic info:
JDK 11
Lein 2
http-kit 2.5.3

Trace:

```
Error: No instances of sun.security.provider.NativePRNG are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=sun.security.provider.NativePRNG.
24
Detailed message:
25
Trace: Object was reached by 
26
	reading field java.security.SecureRandom.secureRandomSpi of
27
		constant java.security.SecureRandom@68066dce reached by 
28
	reading field sun.security.ssl.SSLContextImpl.secureRandom of
29
		constant sun.security.ssl.SSLContextImpl$TLSContext@1ea24385 reached by 
30
	reading field javax.net.ssl.SSLContext.contextSpi of
31
		constant javax.net.ssl.SSLContext@9536373 reached by 
32
	scanning method org.httpkit.client.ClientSslEngineFactory.getContextInstance(ClientSslEngineFactory.java:29)
33
Call path from entry point to org.httpkit.client.ClientSslEngineFactory.getContextInstance(): 
34
	at org.httpkit.client.ClientSslEngineFactory.getContextInstance(ClientSslEngineFactory.java:29)
35
	at org.httpkit.client.ClientSslEngineFactory.trustAnybody(ClientSslEngineFactory.java:33)
36
	at org.httpkit.client$coerce_req.invokeStatic(client.clj:68)
37
	at org.httpkit.client$coerce_req.invoke(client.clj:60)
38
	at clojure.instant.proxy$java.lang.ThreadLocal$ff19274a.hashCode(Unknown Source)
39
	at java.util.HashMap.hash(HashMap.java:339)
40
	at java.util.HashMap.get(HashMap.java:552)
41
	at com.oracle.svm.core.jdk.Target_java_nio_charset_Charset.lookup(CharsetSubstitutions.java:74)
42
	at java.nio.charset.Charset.isSupported(Charset.java:503)
43
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY:Ljava_nio_charset_Charset_2_0002eisSupported_00028Ljava_lang_String_2_00029Z(generated:0)
44
```

I know there was a [issue raised about this](https://github.com/http-kit/http-kit/issues/463) and I've tried all the variations, such as:

```
--initialize-at-run-time=org.httpkit.client.ClientSslEngineFactory\$SSLHolder
```

```
--initialize-at-run-time=org.httpkit.client.ClientSslEngineFactory\$$SSLHolder
```

```
--initialize-at-run-time=org.httpkit.client.ClientSslEngineFactory$SSLHolder 
```

And, finally

```
--initialize-at-run-time=org.httpkit.client.ClientSslEngineFactory
```

And yet to no avail. I do not have this issue on my local setup (M1 Mac), but this happens on Github Actions (for both `ubuntu-latest` and `macos-latest`). I do not know what system does Github Actions use in the background, but I get a feeling it is mungling the dollar sign somehow. Not really sure what to do about this other than refactor my code to not use http-kit to get around this issue. All help is appreciated.

**Comment by askonomm** [comment]
Update: managed to get it working, apparently in Github Actions you have to do it like this:

```
--initialize-at-run-time=org.httpkit.client.ClientSslEngineFactory\${{ '$SSLHolder' }}
```

It would be cool if these different edgecases would be documented in the README maybe? What do you think? I could make a PR for that.

**Comment by borkdude** [comment]
I think it's better to just put this config in `resources/META-INF/native-image/http-kit/http-kit/native-image.properties` (e.g.:
https://github.com/babashka/babashka/blob/master/resources/META-INF/native-image/babashka/babashka/native-image.properties)
than to account for every tool's syntax edge case. The bash case is already documented in the README.

**Comment by borkdude** [comment]
Putting the config there will make graalvm automatically pick up on it so you don't have to provide these arguments when using this dependency.

**Comment by askonomm** [comment]
Ah cool! Yeah that is a way more solid solution indeed, thank you @borkdude!

**Comment by borkdude** [comment]
@askonomm Perhaps you can make a PR for that?

**Comment by askonomm** [comment]
PR created in #477.
