### ISSUE TITLE
Issue with locking Files served to clients

### ISSUE THREAD

**Issue by ikappaki** [http-kit/http-kit#478]
There is a side effect with a Files serving optimisation in http-kit, at least on MS-Windows, that can result in preventing hot reloading of js files to the web browser during a cljs development session. The issue is with http-kit locking files that it served of size greater than 20 MB, preventing them to be updated by external processes.

In my case for example, it breaks the shadow-cljs REPL development session when the resulting cljs to js file under development is >= 20 MB. The js app is served to the web browser but http-kit locks the js file. When the developer makes changes in the cljs source code, the code is complied to js and hot reloaded to the web browser. Shadow then also tries to sync the modified js code to the local .js file but because it is locked by http-kit it fails the session, preventing the user from doing any further development.

On windows, the error that shadow-cljs eventually returns is

```
The requested operation cannot be performed on a file 
with a user-mapped section open
```

I assume other cljs hot reloading tools such as figwheel to fail in a similar manner.

My expectation is that http-kit should not put locks on served files that can be updated during a session.

Below is a minimal project that demonstrates that http-kit puts a lock on files that is served that are equal or greater to 20 Mb.

*deps.edn*:
```clojure
{:paths ["src"]
 :deps {org.clojure/clojure {:mvn/version "1.10.3"}
        http-kit/http-kit {:mvn/version "2.5.3"}}}
```

*src/issue/http_kit_mapped_file.cljs*:
```clojure
(ns issue.http-kit-mapped-file
  "Example http-kit program to demonstrate locking of served files when
  their size exceeds 20 Mb."
  (:gen-class)
  (:import [java.io File FileInputStream FileOutputStream])
  (:require [org.httpkit.server :as s]))

(defn ^File file-gen
  "Creates a dummy MB.js File in the current directory of size MB megabytes.

  Returns the File."
  ([Mb]
   (let [file (File. (str Mb ".js" ))
         path (.getAbsolutePath file)]
     (with-open [w (clojure.java.io/writer file)]
       (.write w (str "/** " path " ") )
       (.write w (str (apply str (repeat (* 1024 1024 Mb) "*"))))
       (.write w "/"))
     (println :file-created-at path)
     file)))

(defn -main
  "Starts the server at port 3003."
  [& _]

  (let [port 3003]
    (println :running-server... :port port)

    (s/run-server
     ;; The handler. When REQUEST URI is /NN, with NN being an integer
     ;; < 26, it creates an NN.js File of size NN in the current
     ;; directory and serves it to the client. Otherwise it sends a
     ;; 404 to the client.
     (fn [{:keys [uri] :as request}]
       (let [Mb (try (Integer/parseInt (subs uri 1))
                     (catch Exception e
                       nil) )]
         (println :requesting :uri uri :Mb Mb)

         (if-not (and  Mb (< Mb 26))
           {:status 404
            :body "invalid request, request size must be < 26."}
           
           (let [file (file-gen Mb)]
             {:status 200
              :body file}))))

     ;; server parameters
     {:port port})))

```

Running `clojure -M -m issue.http-kit-mapped-file` starts the server at port 3003 with a handler that serves requests at /NN where NN is an integer (responds with 404 otherwise). The handler will create a dummy NN.js File in the current directory of size NN MB and serves them to the client.

Thus for example, if we open the browser at http://localhost:3003/10, the http-kit will create a ./10.js file of 10 MB, and serve it to the browser. This file can be immediately modified or removed (say from the command prompt on windows).

e.g. from a windows command prompt, the file is deleted without error
```
> del 10.js
```

If we open the browser though at http://localhost:3003/21, which will have the server create a ./21.js file of 21 MB and serve it to the web browser, the file cannot be modified or deleted because it is locked:

e.g. from a windows command prompt:
```
>del 21.js
The process cannot access the file because it is being used by another process.
```

Th 20 Mb threshold is defined as hard coded valued in [HttpUtils:ReadAll(File)](https://github.com/http-kit/http-kit/blob/5cd3adbf92863fea6d5ae5aabbb06b86945fac66/src/java/org/httpkit/HttpUtils.java#L298) which decides whether to use a `java.nio.MappedByteBuffer` for reading files.

Patch with a possible solution to follow.

**Comment by ptaoussanis** [comment]
Closing since #479 is merged, but feel free to re-open if this should still be discussed further. Thanks!
