### ISSUE TITLE
How to fire multiple HTTP requests in parallel?

### ISSUE THREAD

**Issue by pheeria** [http-kit/http-kit#486]
Hi 🖖

I'm new to your library and to Clojure in general.
My question is: how can I fire multiple HTTP requests in parallel?

I have found the following example in [your docs](https://http-kit.github.io/client.html#combined):
```clj
(let [urls ["http://server.com/api/1" "http://server.com/api/2"
            "http://server.com/api/3"]
      ;; send the request concurrently (asynchronously)
      futures (doall (map http/get urls))]
  (doseq [resp futures]
    ;; wait for server response synchronously
    (println (-> @resp :opts :url) " status: " (:status @resp)))
```
Regarding the code above, I have the following questions:
1. Do we need to `doall`? Afaik, this should force eager evaluation.
2. Is this code going to fire all of the requests at immediately and wait until **all of them return**?

I have come up with the following code:
```clj
 (let [futures (map http/get urls)
        responses (map deref futures)
        filtered (map filter-top-5 responses)]
    (apply concat filtered))
```
Am I correct to assume that it:
1. Fires all the requests
2. Waits until **all of them return**
3. Proceeds with filtering and concatenation of the results?

Is there a better way to things in parallel, assuming I already use `:keepalive` option?
Is there a way to process/filters responses as they arrive and concatenate after everything was done?

Thank you for your work!
Olzhas

**Comment by borkdude** [comment]
1 The doall is only used here to realize spawning the futures, it doesn't actually block on those futures.
2 Yes. 

1 Yes
2 map deref is going to return a seq of deref-ed values, and you're der-ing the futures in a specific order, so you're going to wait for the first one, then the second one, etc, until the requests are all finished
3 Yes

Is there a way to get the result of the first response? Yes:

``` clojure
(def first-response (promise))
(http/get url (fn [response] (deliver first-response response)))
@first-response
```

**Comment by pheeria** [comment]
Thank you for such a detailed explanation, @borkdude!
Just wanted to verify if I understand it correctly:

> map deref is going to return a seq of deref-ed values, and you're der-ing the futures in a specific order, so you're going to wait for the first one, then the second one, etc, until the requests are all finished

Let's say we have three requests that will resolve in `[200ms, 250ms, 180ms]`. If we were to `map deref`, does it mean the  first will be resolved in `200ms`, then the second one will follow, however since the requests were fired simultaneously, we'd wait only for the remaining `50ms` and the last request will have been resolved by then, meaning that the whole sequence will resolve in `~250ms`?

If the above written is correct, then using the in order of arrival approach can give us a benefit of also adding the response processing as the part of the callback, right? However if the response processing isn't resource-intensive, I see a little benefit in involving promises and atoms, since the total time will not vary significantly using either of the ways. Am I thinking in the right direction?

**Comment by borkdude** [comment]
Correct! 

Correct!

**Comment by pheeria** [comment]
Thank you very much and have a happy new year! 🖖
