### ISSUE TITLE
Content-Length header set on Websocket upgrade request 

### ISSUE THREAD

**Issue by restenb** [http-kit/http-kit#498]
HTTP requests with empty body will have `Content-Length 0` set by default by the HttpEncode class, whenever `Transfer-Encoding` is not present. See the following snippet from HttpUtils.java, line 454: 
            
```
if (!CHUNKED.equals(headers.get("Transfer-Encoding"))) {
   if (bodyBuffer != null) {
      // trust the computed length
      headers.putOrReplace(CONTENT_LENGTH, Integer.toString(bodyBuffer.remaining()));
   } else {
      headers.putOrReplace(CONTENT_LENGTH, "0");
   }
}

```

This will include, among other things, the WebSocket upgrade response. Setting `Content-Length` on this was causing problems with the HTTP proxy on Azure App Service, which terminated the connection instead of relaying the response. 

While Microsoft might fix the above, we also noticed this from the standard:
https://www.rfc-editor.org/rfc/rfc7230#section-3.3.2

> A server MUST NOT send a Content-Length header field in any response
> with a status code of 1xx (Informational) or 204 (No Content).
> 

https://www.rfc-editor.org/rfc/rfc7230#section-3.3.2
>    1.  Any response to a HEAD request and any response with a 1xx
>        (Informational), 204 (No Content), or 304 (Not Modified) status
>        code is always terminated by the first empty line after the
>        header fields, regardless of the header fields present in the
>        message, and thus cannot contain a message body.

So at the very least `Content-Length` seems superfluous in these cases, even though the body size _is_ 0 bytes, and it may cause issues with proxies as we have seen with Azure App Service. 

We also tested two other server implementations; spring websockets and jetty 10. Neither sets `Content-Length` on the upgrade request. So we suggest a change here that takes at least the Websocket upgrade request headers into account before setting `Content-Length`. We have a working prototype of this that we can submit as a PR.

**Comment by ptaoussanis** [comment]
@restenb Hi Roger, thanks for the clear and detailed report 👍 
Would love to see a PR, thanks.

Planning to cut a major new http-kit release in the next few weeks - so would be a great time to get this addressed.

**Comment by davidhjp01** [comment]
Created a pull request at https://github.com/http-kit/http-kit/pull/499

**Comment by ptaoussanis** [comment]
Merging your PR now, thanks! 👍
