### ISSUE TITLE
Deflate-frame support

### ISSUE THREAD

**Issue by galdolber** [http-kit/http-kit#50]
Is there any plan to support the deflate extension?

Sec-WebSocket-Extensions:x-webkit-deflate-frame

**Comment by brunchboy** [comment]
I wonder if browsers are starting to expect this? I can’t get WebSocket connections to work to http-kit. In Safari attempts result in: `[Error] WebSocket connection to 'ws://localhost:16000/ws' failed: Compressed bit must be 0 if no negotiated deflate-frame extension (1, line 0)`, and in Chrome I see: `WebSocket connection to 'ws://localhost:16000/ws' failed: Invalid frame header`. So for now I have to give up on the idea of WebSockets, and just have my page poll for new data frequently.

**Comment by pate** [comment]
@brunchboy I followed the sente README to the letter, and I'm also getting the exact same errors in Chrome and Safari.

**Comment by brunchboy** [comment]
I’d love for this to work, so I can stop wasting (albeit small amounts of) CPU polling every 30ms.

**Comment by pate** [comment]
@brunchboy my problem was caused by ring middleware.

**Comment by brunchboy** [comment]
Oh, really? Which piece of middleware, and how were you able to resolve it?

**Comment by brunchboy** [comment]
I really wish I were able to use this functionality. @pate can you tell me what middleware was the issue and how you resolved it?

**Comment by ptaoussanis** [comment]
@pate or anyone else have any input on this? Thanks!

**Comment by brunchboy** [comment]
Even if not, I don’t think it was inappropriate of you to close the issue, if @pate is correct, the problem is not with http-kit.

**Comment by ptaoussanis** [comment]
@brunchboy Thanks!
