### ISSUE TITLE
Add native-image test to CI

### ISSUE THREAD

**Issue by borkdude** [http-kit/http-kit#509]
@ptaoussanis Now that we have an actively running Github action, I think we should add a native image test to prevent regressions in that area. I'm willing to do a PR.

**Comment by borkdude** [comment]
@ptaoussanis I'm working on these and I indeed found some regressions. Please wait with releasing 2.7 if you can, I'll fix these ASAP.

**Comment by ptaoussanis** [comment]
Please take your time Michiel, there's no rush. Thanks a lot for thinking of and taking care of this- much appreciated 👍

**Comment by ptaoussanis** [comment]
Closing since #511 has been merged 👍
