### ISSUE TITLE
Provide out-of-the-box support for GraalVM Native Image.

### ISSUE THREAD

**Issue by fniephaus** [http-kit/http-kit#515]
https://github.com/http-kit/http-kit/pull/460 extended the README.md with instructions how to compile http-kit with GraalVM Native Image. https://github.com/http-kit/http-kit/commit/618b4057c8381578413c75142363ce7dafd509ee added a `native-image.properties` file, which automates the class initialization part.
To automate the reflection part, I think all you have to do is to create a `reflect-config.json` in the [same directory](https://github.com/http-kit/http-kit/tree/618b4057c8381578413c75142363ce7dafd509ee/resources/META-INF/native-image/http-kit/http-kit) with the [required content](https://github.com/http-kit/http-kit/tree/23aa09f6b00fc640b4677466240e57068fbb6ca3#reflection). More information on this can be found [here](https://www.graalvm.org/22.3/reference-manual/native-image/metadata/#specifying-reflection-metadata-in-json). With that, the instructions for GraalVM support can be dropped from the README.md.

Full disclosure: I work on the GraalVM team.

**Comment by borkdude** [comment]
@fniephaus Thanks for reaching out. I'm aware of this, but I haven't gotten around to update the README ;-). The reflection config is also not necessary anymore. This project contains a `test-native` project which tests the project with native-image on CI and doesn't require any configuration for this project and prevents future regressions.

**Comment by borkdude** [comment]
Submitted a PR.
