### ISSUE TITLE
Unexpected Compile Dependency on `cider/cider-nrepl`

### ISSUE THREAD

**Issue by harold** [http-kit/http-kit#520]
Hello - thanks as ever for `http-kit`, we serve everything with it, and it serves (no pun intended!) us so well. I'm so glad to see it continue to thrive.

I tried 2.7.0-beta2 this week and found a surprising dependency on `cider/cider-nrepl`...

From this page: https://mvnrepository.com/artifact/http-kit/http-kit/2.7.0-beta2
![image](https://user-images.githubusercontent.com/7443/235951923-7d143a2b-e8e0-4862-9848-6d2d62725d7d.png)

This seems odd, since the only reference I see to that package is here:
https://github.com/http-kit/http-kit/blob/d10ea7de76bd748a14a1c7329d1c615ca3e571be/project.clj#L19

And that's in the `:plugins`, which (and I'm no lein expert) I wouldn't expect to make it into the `.pom` as that kind of full-fledged dependency.

Let me know what more I can do or provide to help - I am happy to investigate further. Thanks again!

**Comment by ptaoussanis** [comment]
@harold Hi Harold, thanks a lot for the report - very clear and detailed!
The dependency was definitely unintentional.

Will get this fixed for the next release 👍

**Comment by ptaoussanis** [comment]
You're very welcome, thanks for the kind words!

I just released a quick hotfix: https://github.com/http-kit/http-kit/releases/tag/v2.7.0-beta3

Cheers :-)

**Comment by harold** [comment]
Beautiful, confirmed as fixed.
