### ISSUE TITLE
Client error: Illegal character in query at index

### ISSUE THREAD

**Issue by IliasDeros** [http-kit/http-kit#522]
Hi, thank you for the hard work on creating such a lean library.

Running this query in browser runs as expected (Authorization failure)
https://production.shippingapis.com/ShippingAPI.dll?API=Verify&XML=%3CAddressValidateRequest%20USERID=%22MYUSERID%22%3E%3CAddress%20ID=%220%22%3E%3CAddress1%20/%3E%3CAddress2%3ENo%20Way%20Out%3C/Address2%3E%3CCity%20/%3E%3CState%20/%3E%3CZip5%3E%3C/Zip5%3E%3CZip4%20/%3E%3C/Address%3E%3C/AddressValidateRequest%3E

Why does running it with `http-kit` throw an error?

```clojure
(println "Response:" @(http-kit/get (str "https://production.shippingapis.com/ShippingAPI.dll?API=Verify&XML="
          "<AddressValidateRequest USERID=\"" userid "\">"
            "<Address ID=\"0\">"
              "<Address1 />"
              "<Address2>" line1 "</Address2>"
              "<City />"
              "<State />"
              "<Zip5>" zip "</Zip5>"
              "<Zip4 />"
            "</Address>"
          "</AddressValidateRequest>")))
;; Response:
;; {:opts {:method :get, :url https://production.shippingapis.com/ShippingAPI.dll?API=Verify&XML=<AddressValidateRequest USERID="MYUSERID"><Address ID="0"><Address1 /><Address2>No Way Out</Address2><City /><State /><Zip5></Zip5><Zip4 /></Address></AddressValidateRequest>}, :error #error {
;;  :cause Illegal character in query at index 67: https://production.shippingapis.com/ShippingAPI.dll?API=Verify&XML=<AddressValidateRequest USERID="MYUSERID"><Address ID="0"><Address1 /><Address2>No Way Out</Address2><City /><State /><Zip5></Zip5><Zip4 /></Address></AddressValidateRequest>
```

**Comment by harold** [comment]
XML in the url? An interesting choice.

Maybe you need to url escape the string before making the request?

**Comment by ptaoussanis** [comment]
@IliasDeros Hi Ilias! @harold is correct. As the error message indicates:

> Illegal character in query at index 67

So you've got an illegal character at position 67 of your string. The 67th character is `\<`, which isn't a [valid URL character](https://www.freecodecamp.org/news/url-encoded-characters-reference/).

The typical way to use a URL like this, is via URL encoding - like your browser example.
The same link above should also give some pointers re: URL encoding.

Hope that helps, cheers! :-)

**Comment by IliasDeros** [comment]
Thanks for the help!
:white_check_mark: Solved with URL encoding:

```
(println "Response:" @(http-kit/get (str "https://production.shippingapis.com/ShippingAPI.dll?API=Verify&XML="
          (java.net.URLEncoder/encode (str "<AddressValidateRequest USERID=\"" userid "\">"
            "<Address ID=\"0\">"
              "<Address1 />"
              "<Address2>" line1 "</Address2>"
              "<City />"
              "<State />"
              "<Zip5>" zip "</Zip5>"
              "<Zip4 />"
            "</Address>"
          "</AddressValidateRequest>")))))
          
;; Response
;; Received fatal alert: handshake_failure
```

**Comment by IliasDeros** [comment]
**Note:** In case anyone stumbles upon this thread, I resolved that `handshake_failure` using the following base docker image change:
``
FROM eclipse-temurin:8-alpine -> FROM amazoncorretto:8-alpine3.17-jdk
```
