### ISSUE TITLE
HttpClient breaks on chunked response with trailer

### ISSUE THREAD

**Issue by leahneukirchen** [http-kit/http-kit#523]
A HTTP/1.1 response that uses `Transfer-Encoding: chunked` but also has Trailers yields an error:

```
"HTTP/1.1 200 OK
Content-Type: application/json
Trailer: ETag
Date: Tue, 23 May 2023 14:25:17 GMT
Transfer-Encoding: chunked
10d
...body...

0
Etag: "/config/ ba05233b"


```

```
{:type org.httpkit.ProtocolException
   :message "Expected an empty line, but found Etag: \"/config/ ba05233b\""
   :at [org.httpkit.client.Decoder readEmptyLine "Decoder.java" 144]}
```

(You can use the `localhost:2019/config/` endpoint of Caddy to test this.)

See RFC2616: https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html#sec3.6.1
> The chunked encoding is ended by any chunk whose size is zero, followed by the trailer, which is terminated by an empty line.

**Comment by leahneukirchen** [comment]
I use the http-kit client to talk to the Caddy configuration API, but it fails to parse the standards-compliant response because a Trailer: is sent with the last chunked part.

**Comment by ptaoussanis** [comment]
> I use the http-kit client to talk to the Caddy configuration API

Can you please provide an example? Something that can be easily reproduced would be ideal, thanks!

**Comment by leahneukirchen** [comment]
Run Caddy (I use 2.6.4 but shouldn't matter too much):

```
% caddy run
2023/05/30 11:35:27.475	INFO	admin	admin endpoint started	{"address": "localhost:2019", "enforce_origin": false, "origins": ["//localhost:2019", "//[::1]:2019", "//127.0.0.1:2019"]}
```

Speak to the API:

```
% clj
Clojure 1.11.1
user=> (require '[org.httpkit.client])
nil
user=> @(org.httpkit.client/get "http://localhost:2019/config/")
{:opts {:method :get, :url "http://localhost:2019/config/"}, :error #error {
 :cause "Expected an empty line, but found Etag: \"/config/ 0e7c22ea\""
 :via
 [{:type org.httpkit.ProtocolException
   :message "Expected an empty line, but found Etag: \"/config/ 0e7c22ea\""
   :at [org.httpkit.client.Decoder readEmptyLine "Decoder.java" 144]}]
 :trace
 [[org.httpkit.client.Decoder readEmptyLine "Decoder.java" 144]
  [org.httpkit.client.Decoder decode "Decoder.java" 112]
  [org.httpkit.client.HttpClient doRead "HttpClient.java" 211]
  [org.httpkit.client.HttpClient run "HttpClient.java" 487]
  [java.lang.Thread run "Thread.java" 829]]}}
```

**Comment by ptaoussanis** [comment]
Great, thanks for the clarification and report 👍

Sounds like a bug in the [client decoder](https://github.com/http-kit/http-kit/blob/98fd1de4fc99880f006d18ff1147b0da24c3246c/src/java/org/httpkit/client/Decoder.java#L81).

PR very welcome if you or someone else would be interested to take a look!

**Comment by ptaoussanis** [comment]
Update: I took a quick stab at addressing this with https://github.com/http-kit/http-kit/commit/110b45e44118e460a793a0a62c86cfdcae961b96.

Looks straight-forward enough, but I'll keep this open for now in case anyone else is available to help review.

**Comment by ptaoussanis** [comment]
I think this can probably be closed. Can re-examine if any issues come up.
