### ISSUE TITLE
Outdated http.async.client fails to compile

### ISSUE THREAD

**Issue by NoahTheDuke** [http-kit/http-kit#530]
Hey friends,

http.async.client, a dependency in the `:dev` profile, fails to compile when used with a version of Clojure later than 1.8. [Here's the PR where it's fixed.](https://github.com/cch1/http.async.client/pull/76) This doesn't matter for downstream users of http-kit as it's a dev-only dependency, but it makes it harder to work on http-kit if we can't use recent versions of Clojure (to verify things like compilation). Updating to version 1.2.0 should be the earliest version that includes the fix.

Thanks so much.

**Comment by ptaoussanis** [comment]
Will be addressed in forthcoming release 👍
