### ISSUE TITLE
Capture number of processors at runtime in a graalvm binary

### ISSUE THREAD

**Issue by borkdude** [http-kit/http-kit#533]
The number of processors are captured in a top level value: 

https://github.com/http-kit/http-kit/blob/ff5802d8a7c59ff84894a0d4ebd5eff775bedb2e/src/org/httpkit/client.clj#L89

https://github.com/http-kit/http-kit/blob/ff5802d8a7c59ff84894a0d4ebd5eff775bedb2e/src/org/httpkit/server.clj#L47

In a GraalVM binary this value is captured at compile time. It'd be better to delay this expression to runtime so it truly captures the number of processors on the user's machine and not that of the build environment.

Happy to follow up with a PR.

**Comment by borkdude** [comment]
PR here: https://github.com/http-kit/http-kit/pull/534

**Comment by ptaoussanis** [comment]
I believe this can be closed now 👍

Ended up taking a slightly different approach since I was anyway planning to introduce some worker utils which also bypass the problem.

Thanks again for the report and work on this! Cheers :-)
