### ISSUE TITLE
2.8.0-beta2 has CIDER dependencies

### ISSUE THREAD

**Issue by borkdude** [http-kit/http-kit#545]
I was about to bump httpkit in babashka, since beta2 solve a real GraalVM issue with virtual threads, but unfortunately this version depends on cider libraries:

``` clojure
http-kit/http-kit 2.8.0-beta2
  . cider/cider-nrepl 0.38.1
    . nrepl/nrepl 1.0.0
    . mx.cider/logjam 0.1.1
```

I'm not comfortable using this version of http-kit since I don't want to pull in the additional dependencies, but I guess I could just add some exclusions to work around it for now (which I realized while writing this issue, D'OH).

**Comment by ptaoussanis** [comment]
That's unintentional, thanks for the report - will get it fixed shortly 👍

**Comment by ptaoussanis** [comment]
`[http-kit "2.8.0-beta3"]` is [on Clojars](https://clojars.org/http-kit/versions/2.8.0-beta3), without the unintended dep 👍

**Comment by borkdude** [comment]
Thanks!
