### ISSUE TITLE
Unix socket benchmark

### ISSUE THREAD

**Issue by tom-adsfund** [http-kit/http-kit#548]
Great to see the benchmark, and virtual threads stuff!

I'm guessing you probably already thought about benchmarking the unix socket, but it would be interesting to see if there's a difference here too.

**Comment by ptaoussanis** [comment]
@tom-adsfund Hi Tom!

The current server benchmarks are implemented using [wrk](https://github.com/wg/wrk), which I [don't believe](https://github.com/wg/wrk/issues/400) currently has support for Unix Domain Sockets.
