### ISSUE TITLE
It will turn headers into camel format

### ISSUE THREAD

**Issue by zhenghub** [http-kit/http-kit#549]
I create a http request using this header option
```clojure
{:headers {"x-tool-gzip" "1"}}
```
But the client will send to the server in this header format:
```
X-Tool-Gzip: 1
```
Could this feature be closed and the headers are sent as they are?

**Comment by ptaoussanis** [comment]
@zhenghub Hi Zheng! Could you please share a little more about your use case? Is there a specific reason that you care about the header case?

Thanks!

**Comment by ptaoussanis** [comment]
Closing as part of issue triage due to inactivity.
