### ISSUE TITLE
Are compojure routes synchronous?

### ISSUE THREAD

**Issue by zentrope** [http-kit/http-kit#55]
When you use `compojure` and don't do any sort of with-channel stuff, does that mean that requests are handled synchronously? In other words, we can never have more than num-worker-threads simultaneous requests?

I see the example for `compojure`. Is the implication that making the body of the function a reference to a function, e.g., 

``` clojure
(defn name-of-fn [req] ...)

(GET "/route/:id" [] 
   name-of-fm)
```

allows requests to be processed asynchronously?

If you don't do that, e.g., 

``` clojure
(GET "/route/:id" [id] 
   (this id) 
   (that id) 
   "<p>okay</p>")
```

then the request is processed synchronously?

**Comment by akaivola** [comment]
I'd like to add to this, `with-channel` does not make anything asyncrohonous by itself. Everything executing within `with-channel` will still block and `with-channel` will return only after you stop blocking. To mitigate this you need to do

```(with-channel req channel
  (go (block-to-your-hearts-content)))```
