### ISSUE TITLE
Transfer-Encoding header with streamed responses

### ISSUE THREAD

**Issue by giorgio-v** [http-kit/http-kit#56]
According to this post[1] the `Transfer-Encoding` header should _not_ be set to `chunked`. I tried to override in the `send!` call, but it seems hard-coded:

```
(server/send!
    channel
    {:headers {"Content-Type" "text/event-stream; charset=utf-8"
                    "Cache-Control" "no-cache"
                    "Transfer-Encoding" "identity"}
     :status 200
     :body (str "data: message from server #" id "\n\n")} false)
```

Also, documentation is not very clear, IMHO, because it doesn’t say anything about the `text/event-stream` header. Granted, http-kit are not the place to explain to Server-Sent events[2] but a pointer to some docs could be helpful.

- [1] http://stackoverflow.com/questions/13590755/eventsource-disconnects-after-first-message
- [2] http://dev.w3.org/html5/eventsource/

**Comment by ptaoussanis** [comment]
Closing this issue as stale, please feel free to reopen if there's new info anyone would like to follow up with.
