### ISSUE TITLE
Add updated WebSocket examples to Wiki

### ISSUE THREAD

**Issue by ptaoussanis** [http-kit/http-kit#570]
The [Wiki](https://github.com/http-kit/http-kit/wiki) could really use simple, up-to-date documentation/examples of how to effectively use WebSocket with http-kit client + server.

With the latest versions of http-kit, there are two ways to do this:

1. Using http-kit's own "AsyncChannel" API
2. Using the standard Ring WebSocket API

It'd be nice to have both explained, and contrasted

# Approach 1

A typical flow would be something like this-

- Your Ring handler uses [as-channel](https://cljdoc.org/d/http-kit/http-kit/CURRENT/api/org.httpkit.server#as-channel) to setup handlers for open/close/receive events. Those handlers will be called on activity, with an arg for the underlying http-kit AsyncChannel.

- You use an atom or something similar to keep track of active channels for server->client messaging.

In this setup, http-kit’s handler threads are used only briefly for the initial request handling at 1. Everything after that is just IO, or app-level threads.

[Sente](https://www.taoensso.com/sente) uses this approach. It’d be a lot of code to look through, but the main relevant bits are probably [here](https://github.com/taoensso/sente/blob/102c5b0b2ca8e1ce931655f146d770287f4a1b8b/src/taoensso/sente/server_adapters/http_kit.clj#L26) and [here](https://github.com/taoensso/sente/blob/102c5b0b2ca8e1ce931655f146d770287f4a1b8b/src/taoensso/sente.cljc#L983).

# Approach 2

James Reeves has written something [here](https://github.com/ring-clojure/ring-examples/tree/master/websocket-chat) that could maybe be ported to http-kit (or at least linked to from http-kit's docs)?

# Assistance welcome!

PR very welcome if someone wanted to help out with this 🙏

The [Wiki files](https://github.com/http-kit/http-kit/tree/master/wiki) are part of the main http-kit repo.

**Comment by jf** [comment]
I'd be happy to write up something for approach 1. Not able at this point in time to do approach 2 though, if that's ok.

**Comment by ptaoussanis** [comment]
@jf Totally okay, thanks Jeffrey!

**Comment by jf** [comment]
I have the PR ready @ptaoussanis , but will definitely need your input / help to really flesh things out. Thanks!

**Comment by ptaoussanis** [comment]
Merged manually, thanks again Jeffrey! 🙏
