### ISSUE TITLE
Question: Response Body size limitation

### ISSUE THREAD

**Issue by kroncatti** [http-kit/http-kit#577]
Folks,

Just trying to understand a little bit better something about how http-kit works.

I would like to understand why is there a limitation of 8mb on response payloads in this piece of code in [here](https://github.com/http-kit/http-kit/blob/master/src/java/org/httpkit/client/RespListener.java#L120-L133). Is there any reasons why isn't this limit bigger ?

**Comment by ptaoussanis** [comment]
@kroncatti Hi Kaleb, I'm not certain on what the original motivation was - but in general I'd suggest that http-kit is not ideal for large responses. For example the client buffers entire responses before sending, and the server uses a single thread for IO iirc.

**Comment by kroncatti** [comment]
Hey @ptaoussanis, thanks for sharing. No problem at all. Just wanted to clarify if there was any specific reason for it. 

Good to know that it is not recommended for large responses.
