### ISSUE TITLE
WebSocket subprotocol support

### ISSUE THREAD

**Issue by cgmartin** [http-kit/http-kit#64]
Is there a way currently to specify a WebSocket subprotocol during the connection handshake? I would like to define a list of subprotocols that can be sent back in a `Sec-WebSocket-Protocol` header:

http://tools.ietf.org/html/rfc6455#section-1.3

```
Additional header fields are used to select options in the WebSocket
Protocol.  Typical options available in this version are the
subprotocol selector (|Sec-WebSocket-Protocol|), list of extensions
support by the client (|Sec-WebSocket-Extensions|), |Origin| header
field, etc.  The |Sec-WebSocket-Protocol| request-header field can be
used to indicate what subprotocols (application-level protocols
layered over the WebSocket Protocol) are acceptable to the client.
The server selects one or none of the acceptable protocols and echoes
that value in its handshake to indicate that it has selected that
protocol.

Sec-WebSocket-Protocol: chat
```

Also to note that might be of interest: I've created a HTTP Kit websocket handler for the WAMP subprotocol at http://cljwamp.us and I've been really been enjoying using HTTP Kit - thanks for sharing it!

**Comment by brandonbloom** [comment]
I came across another use-case for customizing the handshake: Sending a "Set-Cookie" header. Would be nice to have some way to customize the handshake headers.

**Comment by theronic** [comment]
Would the Websocket handshake be an appropriate place to authenticate websocket connections, where the handshake looks for some headers or data in the Upgrade request? On client websocket connection, server would issue a session token based on initial data or headers, which would have to be verifiable going forward.
