### ISSUE TITLE
LineTooLargeException querying riak with http-kit

### ISSUE THREAD

**Issue by h3x3d** [http-kit/http-kit#88]
Riak send's some object metadata (which can be large) through http headers.

Increasing max line size inside java code fixes issue.

```
public Decoder(IRespListener listener, HttpMethod method) {
        this.listener = listener;
        this.method = method;
        lineReader = new LineReader(8096); // Here
}
```

**Comment by ptaoussanis** [comment]
Hi there, doing issue triage - is this question still relevant or can it be closed? Thanks!
